
import type { Puzzle } from '@/lib/types';

export const dummyPuzzles: Puzzle[] = [
  {
    id: 'prophet-noah-ark',
    title: 'Prophet Nuh\'s (AS) Ark',
    description: 'Piece together the image of Prophet Nuh\'s (Noah) ark and the animals.',
    imageUrl: '/assets/images/games/puzzles/puzzle-prophet-noah-ark.png',
    imageAiHint: 'noah ark animals',
    pieces: 12,
  },
  {
    id: 'kaaba-puzzle',
    title: 'The Holy Kaaba',
    description: 'Assemble the puzzle of the Kaaba, the most sacred site in Islam.',
    imageUrl: '/assets/images/games/puzzles/puzzle-kaaba-puzzle.png',
    imageAiHint: 'kaaba mecca pilgrimage',
    pieces: 24,
  },
  {
    id: 'mosque-interior',
    title: 'Beautiful Mosque Interior',
    description: 'Complete the puzzle of a stunning mosque interior design.',
    imageUrl: '/assets/images/games/puzzles/puzzle-mosque-interior.png',
    imageAiHint: 'mosque interior colorful',
    pieces: 36,
  },
  {
    id: 'arabic-calligraphy-peace',
    title: 'Calligraphy: As-Salam',
    description: 'Assemble a beautiful Arabic calligraphy piece meaning "Peace".',
    imageUrl: '/assets/images/games/puzzles/puzzle-arabic-calligraphy-peace.png',
    imageAiHint: 'arabic calligraphy peace',
    pieces: 20,
  },
  {
    id: 'children-praying-puzzle',
    title: 'Children Praying Together',
    description: 'A heartwarming scene of children praying in a mosque.',
    imageUrl: '/assets/images/games/puzzles/puzzle-children-praying-puzzle.png',
    imageAiHint: 'children praying mosque',
    pieces: 16,
  },
  {
    id: 'ramadan-lanterns-puzzle',
    title: 'Ramadan Lanterns',
    description: 'Piece together a colorful scene of Ramadan lanterns at night.',
    imageUrl: '/assets/images/games/puzzles/puzzle-ramadan-lanterns-puzzle.png',
    imageAiHint: 'ramadan lanterns night',
    pieces: 25,
  },
  {
    id: 'islamic-geometric-pattern',
    title: 'Islamic Geometric Pattern',
    description: 'Solve a puzzle featuring intricate Islamic geometric art.',
    imageUrl: '/assets/images/games/puzzles/puzzle-islamic-geometric-pattern.png',
    imageAiHint: 'islamic pattern geometric',
    pieces: 30,
  },
  {
    id: 'family-iftar-puzzle',
    title: 'Family Iftar Time',
    description: 'A puzzle showing a family breaking their fast together during Ramadan.',
    imageUrl: '/assets/images/games/puzzles/puzzle-family-iftar-puzzle.png',
    imageAiHint: 'family iftar meal',
    pieces: 24,
  },
  {
    id: 'eid-celebration-puzzle',
    title: 'Eid Celebration Fun',
    description: 'Capture the joy of Eid with this festive puzzle.',
    imageUrl: '/assets/images/games/puzzles/puzzle-eid-celebration-puzzle.png',
    imageAiHint: 'eid celebration kids',
    pieces: 18,
  },
  {
    id: 'learning-quran-puzzle',
    title: 'Learning Quran Together',
    description: 'Kids learning the Quran with their teacher.',
    imageUrl: '/assets/images/games/puzzles/puzzle-learning-quran-puzzle.png',
    imageAiHint: 'kids quran teacher',
    pieces: 20,
  },
];
