import type { Reward } from '@/lib/types';

export const dummyRewards: Reward[] = [
  {
    id: 'badge-story-explorer',
    title: 'Story Explorer Badge',
    description: 'Awarded for completing your first story.',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge scroll adventure',
    pointsRequired: 10,
  },
  {
    id: 'badge-dua-learner',
    title: 'Dua Learner Badge',
    description: 'Awarded for learning 3 Duas.',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge praying hands',
    pointsRequired: 15, // 3 duas * 5 points
  },
  {
    id: 'badge-quran-reflecter',
    title: 'Quran Reflecter Badge',
    description: 'Awarded for reflecting on 3 Quranic verses.',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge quran open',
    pointsRequired: 21, // 3 verses * 7 points
  },
  {
    id: 'badge-quiz-whiz',
    title: 'Quiz Whiz Badge',
    description: 'Awarded for scoring perfectly on a quiz.',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge brain lightbulb',
    pointsRequired: 10, // A quiz gives max 10 points
  },
  {
    id: 'virtual-prayer-mat',
    title: 'Virtual Prayer Mat',
    description: 'A beautiful virtual prayer mat for your collection.',
    type: 'virtual_item',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'prayer rug colorful',
    pointsRequired: 50,
  },
  {
    id: 'aalim-star-student',
    title: 'Aalim\'s Star Student',
    description: 'Awarded by Aalim for excellent interaction!',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'star gold shiny',
    // No points required, awarded by AI
  },
  {
    id: 'badge-puzzle-master',
    title: 'Puzzle Master Badge',
    description: 'Awarded for completing 3 puzzles.',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge jigsaw complete',
    pointsRequired: 25,
  },
  {
    id: 'wallpaper-kaaba',
    title: 'Kaaba Wallpaper',
    description: 'A beautiful Kaaba wallpaper for your device.',
    type: 'wallpaper',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'kaaba art majestic',
    pointsRequired: 75,
  },
  {
    id: 'badge-memory-champ',
    title: 'Memory Champ Badge',
    description: 'Awarded for winning 3 memory match games.',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge brain gears',
    pointsRequired: 30,
  },
  {
    id: 'virtual-tasbih',
    title: 'Colorful Virtual Tasbih',
    description: 'A set of colorful virtual tasbih beads.',
    type: 'virtual_item',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'tasbih beads vibrant',
    pointsRequired: 40,
  },
  {
    id: 'badge-knowledge-seeker',
    title: 'Knowledge Seeker',
    description: 'Completed 5 stories and 5 quizzes!',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge open book',
    pointsRequired: 100,
  },
  {
    id: 'avatar-smile-face',
    title: 'Smiling Face Accessory',
    description: 'A cheerful smiling face for your avatar.',
    type: 'avatar_accessory',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'avatar smile happy',
    pointsRequired: 20,
  },
  {
    id: 'badge-ramadan-expert',
    title: 'Ramadan Expert Badge',
    description: 'Completed a Ramadan quiz and learned 2 Ramadan duas.',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge lantern crescent',
    pointsRequired: 35,
  },
  {
    id: 'wallpaper-mosque-silhouette',
    title: 'Mosque Silhouette Wallpaper',
    description: 'A serene mosque silhouette at sunset.',
    type: 'wallpaper',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'mosque sunset silhouette',
    pointsRequired: 60,
  },
  {
    id: 'badge-perfect-attendance',
    title: 'Perfect Attendance',
    description: 'Visited the app 7 days in a row (conceptual).',
    type: 'badge',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'badge calendar star',
    pointsRequired: 0, // Awarded by system logic
  },
  {
    id: 'virtual-eid-balloon',
    title: 'Virtual Eid Balloon',
    description: 'A festive virtual balloon for Eid!',
    type: 'virtual_item',
    iconUrl: 'https://placehold.co/100x100.png',
    imageAiHint: 'eid balloon colorful',
    pointsRequired: 15,
  },
];
