import type { Story } from '@/lib/types';

export const dummyStories: Story[] = [
  {
    id: 'prophet-yunus-and-the-whale',
    title: 'Prophet Yunus (AS) and the Whale',
    description: 'Learn about patience and repentance from the story of Prophet Yunus (AS).',
    moral: 'Always be patient and seek forgiveness from Allah.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'whale ocean prophet',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Prophet Yunus (Jonah) was a messenger of Allah sent to the people of Nineveh. He called them to worship Allah alone, but they initially rejected his message.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Prophet Yunus preaching', aiHint: 'man preaching town' },
      { type: 'paragraph', text: 'Feeling frustrated, Prophet Yunus left his people without Allah\'s permission. He boarded a ship, but a great storm arose.' },
      { type: 'paragraph', text: 'To save the ship, the crew decided to cast one person overboard, and the lot fell on Yunus (AS). He was swallowed by a giant whale.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Whale swallowing Prophet Yunus', aiHint: 'whale sea storm' },
      { type: 'paragraph', text: 'Inside the whale\'s belly, in darkness, Prophet Yunus realized his mistake and prayed to Allah: "La ilaha illa Anta, Subhanaka, inni kuntu minaz-zalimin" (There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers).' },
      { type: 'paragraph', text: 'Allah, in His mercy, commanded the whale to cast Prophet Yunus onto the shore. He was weak but safe.' },
      { type: 'decision', prompt: 'What should Prophet Yunus do next?', choices: [
        { text: 'Rest and recover', nextNodeIndex: 8 },
        { text: 'Return to his people', nextNodeIndex: 8 },
      ]},
      { type: 'paragraph', text: 'Allah then caused a plant to grow, providing him with food and shelter. Prophet Yunus (AS) returned to his people, who had repented and believed in Allah. They were forgiven and blessed.' },
      { type: 'paragraph', text: 'This story teaches us the importance of patience, seeking Allah\'s forgiveness, and never losing hope in His mercy.' },
    ],
  },
  {
    id: 'the-honest-shepherd',
    title: 'The Honest Shepherd Boy',
    description: 'A tale about the importance of honesty, even when no one is watching.',
    moral: 'Honesty is a virtue that pleases Allah and earns trust.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'shepherd sheep hills',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Once, there was a young shepherd boy who looked after a flock of sheep for a wealthy man.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Shepherd boy with sheep', aiHint: 'boy sheep field' },
      { type: 'paragraph', text: 'One day, a traveler passed by and offered to buy a sheep. The boy refused, saying, "These sheep are not mine. I am only entrusted to care for them."' },
      { type: 'paragraph', text: 'The traveler, testing him, said, "You can tell your master a wolf ate one." But the boy replied, "My master may not see me, but Allah sees me."' },
      { type: 'paragraph', text: 'The traveler was impressed by the boy\'s honesty. This story teaches us that true honesty is being truthful even when no one is looking, because Allah is always watching.' },
    ],
  },
  {
    id: 'kindness-to-animals',
    title: 'Kindness to Animals in Islam',
    description: 'Discover how Islam teaches us to be kind to all creatures.',
    moral: 'Being kind to animals is an important part of Islamic teachings.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'child cat animals',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Islam emphasizes compassion and mercy towards all living beings, including animals. The Prophet Muhammad (peace be upon him) taught his followers to treat animals with kindness and respect.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Person feeding a cat', aiHint: 'hand feeding kitten' },
      { type: 'paragraph', text: 'There is a famous Hadith about a woman who was forgiven her sins because she gave water to a thirsty dog. This shows the great reward for being kind to animals.' },
      { type: 'paragraph', text: 'Conversely, another Hadith tells of a woman who was punished for mistreating a cat by imprisoning it without food or water.' },
      { type: 'paragraph', text: 'We should provide food and water for animals under our care, not overburden them, and avoid causing them any harm or distress.' },
    ],
  },
  {
    id: 'prophet-adam-creation',
    title: 'The Story of Prophet Adam (AS)',
    description: 'Learn about the creation of the first man, Prophet Adam (AS).',
    moral: 'Obey Allah and seek forgiveness when you make a mistake.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'garden paradise firstman',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Allah created Prophet Adam (AS) from clay and breathed life into him. He taught Adam the names of all things.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Allah creating Adam', aiHint: 'light hands clay' },
      { type: 'paragraph', text: 'Adam (AS) and Hawa (Eve) lived peacefully in Jannah (Paradise). Allah allowed them to enjoy everything except the fruit of one specific tree.' },
      { type: 'paragraph', text: 'Shaytan (Satan) tricked them into eating from the forbidden tree. They disobeyed Allah.'},
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Forbidden fruit', aiHint: 'glowing fruit tree' },
      { type: 'paragraph', text: 'Adam (AS) and Hawa (Eve) immediately felt regret and asked Allah for forgiveness. Allah, The Most Merciful, forgave them but sent them to live on Earth as a test.'},
      { type: 'paragraph', text: 'This story teaches us about obedience, repentance, and Allah\'s vast mercy.' },
    ],
  },
  {
    id: 'prophet-nuh-ark',
    title: 'Prophet Nuh (AS) and the Ark',
    description: 'The story of Prophet Nuh (Noah) and the great flood.',
    moral: 'Trust in Allah\'s plan and persevere in doing good.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'ark animals flood',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Prophet Nuh (AS) preached to his people for many years, but most of them refused to believe.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Nuh preaching', aiHint: 'oldman speaking crowd' },
      { type: 'paragraph', text: 'Allah commanded Nuh (AS) to build a huge ark. People mocked him, but he continued his work with faith.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Nuh building ark', aiHint: 'man building boat' },
      { type: 'paragraph', text: 'When the ark was ready, Allah told Nuh (AS) to take pairs of every animal and the believers with him.' },
      { type: 'paragraph', text: 'Then, a great flood covered the land, and only those on the ark were saved. This story shows Allah\'s power and justice.' },
    ],
  },
  {
    id: 'prophet-ibrahim-fire',
    title: 'Prophet Ibrahim (AS) and the Fire',
    description: 'The miracle of Prophet Ibrahim (Abraham) being saved from the fire.',
    moral: 'Have unwavering faith in Allah, even in the face of great danger.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'fire miracle prophet',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Prophet Ibrahim (AS) called his people to worship Allah alone and stop worshipping idols.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Ibrahim and idols', aiHint: 'man idols stone' },
      { type: 'paragraph', text: 'The king and his people became angry and decided to throw Ibrahim (AS) into a huge fire.' },
      { type: 'paragraph', text: 'But Allah commanded the fire: "O fire, be coolness and safety upon Ibrahim." The fire did not harm him at all.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Ibrahim safe in fire', aiHint: 'man fire unharmed' },
      { type: 'paragraph', text: 'This miracle showed Allah\'s power and protected His prophet. It teaches us to stand for truth and trust Allah completely.' },
    ],
  },
  {
    id: 'prophet-musa-red-sea',
    title: 'Prophet Musa (AS) and the Red Sea',
    description: 'How Prophet Musa (Moses) led his people across the Red Sea.',
    moral: 'Allah can make a way where there seems to be no way.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'sea parting prophet',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Pharaoh and his army chased Prophet Musa (AS) and the Children of Israel to the edge of the Red Sea.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'People by the sea', aiHint: 'crowd sea escape' },
      { type: 'paragraph', text: 'With the sea in front and the enemy behind, the people felt trapped. But Musa (AS) had faith in Allah.' },
      { type: 'paragraph', text: 'Allah commanded Musa (AS) to strike the sea with his staff. The sea parted, creating a dry path for them to cross.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Sea parting', aiHint: 'ocean split path' },
      { type: 'paragraph', text: 'After they crossed safely, the sea closed in on Pharaoh and his army, drowning them. This story shows Allah\'s ultimate power and protection for believers.' },
    ],
  },
  {
    id: 'prophet-muhammad-cave',
    title: 'Prophet Muhammad (PBUH) in Cave Thawr',
    description: 'The story of Hijrah and protection in the cave.',
    moral: 'Allah protects those who trust in Him.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'cave spiderweb birdnest',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'When Prophet Muhammad (PBUH) and Abu Bakr (RA) were migrating to Madinah (Hijrah), they hid in Cave Thawr.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Cave entrance', aiHint: 'mountain cave entrance' },
      { type: 'paragraph', text: 'Their enemies were searching for them and came very close to the cave entrance.' },
      { type: 'paragraph', text: 'By Allah\'s command, a spider spun a web across the cave mouth, and a dove laid eggs, making it seem undisturbed.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Spiderweb on cave', aiHint: 'spiderweb bird cave' },
      { type: 'paragraph', text: 'The searchers saw this and thought no one could be inside, so they left. Allah protected His Prophet and his companion.' },
    ],
  },
  {
    id: 'the-boy-and-the-king',
    title: 'The Boy and the King (Ashab al-Ukhdud)',
    description: 'A story of faith and perseverance against a tyrannical king.',
    moral: 'True faith can move mountains and inspire others, even in death.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'boy king faith',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'A young boy learned about true faith from a believer, despite the king\'s magician trying to teach him magic.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Boy learning', aiHint: 'boy oldman teaching' },
      { type: 'paragraph', text: 'The boy performed miracles in Allah\'s name, and many people started to believe.' },
      { type: 'paragraph', text: 'The king became furious and tried to kill the boy multiple times, but failed. The boy told the king he could only be killed if he shot an arrow in Allah\'s name.' },
      { type: 'paragraph', text: 'The king did so, and the boy died. Seeing this, many more people declared their faith, leading the king to persecute them.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'People by fire trench', aiHint: 'crowd fire faith' },
      { type: 'paragraph', text: 'This story highlights ultimate trust in Allah and the power of sincere faith.' },
    ],
  },
  {
    id: 'the-value-of-salam',
    title: 'The Value of Saying Salam',
    description: 'Learn the importance and blessings of the Islamic greeting.',
    moral: 'Spread peace and kindness by greeting others with "Assalamu Alaikum".',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'kids greeting smile',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: '"Assalamu Alaikum" means "Peace be upon you". It\'s a beautiful greeting in Islam.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Children greeting', aiHint: 'children waving smile' },
      { type: 'paragraph', text: 'Prophet Muhammad (PBUH) taught us to say Salam to people we know and even those we don\'t know.' },
      { type: 'paragraph', text: 'Saying Salam spreads love, friendship, and earns rewards from Allah.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Hands shaking', aiHint: 'hands shake peace' },
      { type: 'paragraph', text: 'When someone greets you with Salam, you should reply with "Wa Alaikum Assalam" (And upon you be peace) or something even better.' },
    ],
  },
  {
    id: 'sharing-is-caring',
    title: 'Sharing is Caring',
    description: 'A story about the joy and reward of sharing with others.',
    moral: 'Sharing brings happiness to others and blessings to ourselves.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'kids sharing toys',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Little Aisha had a box of colorful crayons. Her friend Fatima didn\'t have any.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Girl with crayons', aiHint: 'girl crayons art' },
      { type: 'paragraph', text: 'Aisha remembered her mother taught her that sharing is a good deed in Islam.' },
      { type: 'decision', prompt: 'What should Aisha do?', choices: [
        { text: 'Keep all crayons to herself', nextNodeIndex: 4 },
        { text: 'Share some crayons with Fatima', nextNodeIndex: 5 },
      ]},
      { type: 'paragraph', text: 'If Aisha keeps them, Fatima might feel sad. (This path can lead to a lesson on empathy)' },
      { type: 'paragraph', text: 'Aisha decided to share her crayons with Fatima. They both drew beautiful pictures together and had so much fun! Sharing made them both happy.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Girls drawing together', aiHint: 'kids drawing happy' },
      { type: 'paragraph', text: 'Allah loves those who are generous and share with others.' },
    ],
  },
];
