
import type { Story } from '@/lib/types';

export const dummyStories: Story[] = [
  {
    id: 'prophet-adam-creation',
    title: 'The Story of Prophet Adam (AS)',
    description: 'Learn about the creation of the first man, Prophet Adam (AS), and his life in Jannah.',
    moral: 'Obey Allah, seek forgiveness when you err, and understand Allah\'s boundless mercy.',
    thumbnailUrl: '/assets/images/stories/prophet-adam-creation-thumbnail.png',
    imageAiHint: 'garden paradise firstman',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Allah, the Most High, decided to create a new being, a Caliph (successor) on Earth. He created Prophet Adam (alayhis salam - peace be upon him) from clay and then breathed life into him.' },
      { type: 'image', url: '/assets/images/stories/prophet-adam-creation-content-0.png', alt: 'Allah creating Adam', aiHint: 'light hands clay creation' },
      { type: 'paragraph', text: 'Allah taught Adam the names of all things, giving him knowledge that even the angels did not possess. The angels were then commanded to prostrate to Adam as a sign of respect, not worship. All did so except Iblis (Satan), who was arrogant and refused.' },
      { type: 'paragraph', text: 'Allah created Hawwa (Eve) from Adam to be his companion. They lived peacefully in Jannah (Paradise), with permission to enjoy all its bounties except for the fruit of one specific tree.' },
      { type: 'image', url: '/assets/images/stories/prophet-adam-creation-content-1.png', alt: 'Adam and Eve in Jannah', aiHint: 'couple paradise garden' },
      { type: 'paragraph', text: 'Iblis, filled with envy, tricked Adam and Hawwa into eating from the forbidden tree, whispering that it would give them eternal life or make them angels.'},
      { type: 'decision', prompt: 'Adam and Hawwa realized they disobeyed Allah. What should they do?', choices: [
        { text: 'Hide their mistake', nextNodeIndex: 7 },
        { text: 'Ask Allah for forgiveness', nextNodeIndex: 6 },
      ]},
      { type: 'paragraph', text: 'Adam (AS) and Hawwa (Eve) immediately felt deep regret. They turned to Allah and prayed the words He taught them: "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers." (Quran 7:23).' },
      { type: 'paragraph', text: 'Allah, in His infinite mercy, forgave them. However, as part of His divine plan, they were sent down to Earth to live, multiply, and be tested. Earth became the dwelling place for humankind.' },
      { type: 'paragraph', text: 'This story teaches us about Allah\'s power of creation, the importance of obedience, the danger of arrogance (from Iblis), the reality of human error, the beauty of repentance, and Allah\'s boundless forgiveness and mercy.' },
    ],
  },
  {
    id: 'prophet-nuh-ark',
    title: 'Prophet Nuh (AS) and the Great Ark',
    description: 'The story of Prophet Nuh (Noah), his call to Tawhid, and the great flood.',
    moral: 'Trust in Allah\'s plan, persevere in righteousness even amidst ridicule, and know that Allah saves the believers.',
    thumbnailUrl: '/assets/images/stories/prophet-nuh-ark-thumbnail.png',
    imageAiHint: 'ark animals flood',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Prophet Nuh (AS) was sent to a people who had strayed into idol worship. For 950 years, he called them to worship Allah alone, patiently and persistently, day and night, in public and in private.' },
      { type: 'image', url: '/assets/images/stories/prophet-nuh-ark-content-0.png', alt: 'Nuh preaching to his people', aiHint: 'oldman speaking crowd idols' },
      { type: 'paragraph', text: 'However, most of his people, especially the arrogant leaders, rejected his message, mocked him, and accused him of being a liar or madman. Only a few, mostly the poor and weak, believed in him.' },
      { type: 'paragraph', text: 'When Nuh (AS) saw their persistence in disbelief, Allah revealed to him that no more of his people would believe. He was commanded to build a massive Ark (ship).' },
      { type: 'image', url: '/assets/images/stories/prophet-nuh-ark-content-1.png', alt: 'Nuh building the Ark', aiHint: 'man building large boat wood' },
      { type: 'paragraph', text: 'As Nuh (AS) built the Ark, the disbelievers ridiculed him, saying, "A ship on dry land?" But he continued, trusting in Allah\'s command.' },
      { type: 'paragraph', text: 'When the Ark was complete, Allah commanded Nuh (AS) to take aboard pairs (male and female) of every kind of animal, his family (except those who disbelieved, like one of his sons and his wife), and the few believers who followed him.' },
      { type: 'decision', prompt: 'The disbelievers see Nuh loading animals and believers onto the Ark. What do they do?', choices: [
        { text: 'They finally believe and join him', nextNodeIndex: 8 },
        { text: 'They continue to mock him', nextNodeIndex: 7 },
      ]},
      { type: 'paragraph', text: 'They continued their mockery, heedless of the impending doom. Then, Allah\'s command came. Water gushed forth from the earth, and rain poured from the sky, causing a tremendous flood that engulfed the land.' },
      { type: 'image', url: '/assets/images/stories/prophet-nuh-ark-content-2.png', alt: 'The Ark in the great flood', aiHint: 'ark huge waves storm' },
      { type: 'paragraph', text: 'The Ark, carrying Nuh (AS) and the believers, floated safely on the waters by Allah\'s protection. All the disbelievers, including Nuh\'s own son who refused to board, were drowned.' },
      { type: 'paragraph', text: 'After many days, the flood subsided, and the Ark came to rest on Mount Judi. Nuh (AS) and the believers disembarked, and a new beginning for humanity started, based on faith in Allah.' },
      { type: 'paragraph', text: 'This story teaches us about patience in Dawah (calling to Allah), perseverance against adversity, the consequences of disbelief and arrogance, and Allah\'s justice and mercy in saving the faithful.' },
    ],
  },
  {
    id: 'prophet-ibrahim-faith',
    title: 'Prophet Ibrahim (AS): Father of Prophets',
    description: 'Discover the unwavering faith and trials of Prophet Ibrahim (Abraham).',
    moral: 'Have pure and unwavering faith in Allah alone, reject idol worship, and be ready to sacrifice for Allah.',
    thumbnailUrl: '/assets/images/stories/prophet-ibrahim-faith-thumbnail.png',
    imageAiHint: 'man stars desert night',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Prophet Ibrahim (AS) lived among a people who worshipped idols, stars, and planets. From a young age, he used his intellect to realize these could not be God.' },
      { type: 'image', url: '/assets/images/stories/prophet-ibrahim-faith-content-0.png', alt: 'Ibrahim questioning idols', aiHint: 'young man statues thinking' },
      { type: 'paragraph', text: 'He bravely challenged his people\'s beliefs and called them to worship Allah, the One True God. He famously destroyed their idols, leaving the largest one intact to show them their powerlessness.' },
      { type: 'paragraph', text: 'For this, he was thrown into a massive fire by the tyrant King Nimrod. But Ibrahim (AS) remained firm in his faith.' },
      { type: 'decision', prompt: 'Ibrahim (AS) is thrown into the fire. What happens?', choices: [
        { text: 'He is burned by the fire', nextNodeIndex: 5 },
        { text: 'Allah saves him miraculously', nextNodeIndex: 4 },
      ]},
      { type: 'paragraph', text: 'Allah commanded the fire: "O fire, be coolness and safety upon Ibrahim." (Quran 21:69). The fire did not harm him at all, a clear miracle for all to see.' },
      { type: 'image', url: '/assets/images/stories/prophet-ibrahim-faith-content-1.png', alt: 'Ibrahim safe in the fire', aiHint: 'man cool fire unharmed' },
      { type: 'paragraph', text: 'Another great trial was when Allah commanded him in a dream to sacrifice his beloved son, Ismail (AS). Both Ibrahim and Ismail showed complete submission to Allah\'s will.' },
      { type: 'paragraph', text: 'Just as Ibrahim (AS) was about to perform the sacrifice, Allah ransomed Ismail (AS) with a great ram. This event is commemorated by Muslims during Eid al-Adha.' },
      { type: 'image', url: '/assets/images/stories/prophet-ibrahim-faith-content-2.png', alt: 'Ibrahim and Ismail with ram', aiHint: 'father son ram mountain' },
      { type: 'paragraph', text: 'Ibrahim (AS), with his son Ismail (AS), also rebuilt the Kaaba in Makkah, the first house of worship dedicated to Allah on Earth.' },
      { type: 'paragraph', text: 'Prophet Ibrahim (AS) is known as Khalilullah (Friend of Allah) and is a role model for his monotheism, wisdom, courage, patience, and complete trust in Allah.' },
    ],
  },
  {
    id: 'prophet-yusuf-trials',
    title: 'Prophet Yusuf (AS): Beauty and Trials',
    description: 'The captivating story of Prophet Yusuf (Joseph), his dreams, hardships, and eventual triumph.',
    moral: 'Patience through trials, forgiveness, and trust in Allah\'s plan leads to ultimate good.',
    thumbnailUrl: '/assets/images/stories/prophet-yusuf-trials-thumbnail.png',
    imageAiHint: 'young man colorful coat',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Prophet Yusuf (AS) was one of the twelve sons of Prophet Yaqub (Jacob AS). He was exceptionally handsome and beloved by his father. One night, he saw a dream where eleven stars, the sun, and the moon prostrated to him.' },
      { type: 'image', url: '/assets/images/stories/prophet-yusuf-trials-content-0.png', alt: 'Yusuf telling his dream', aiHint: 'boy father dream stars' },
      { type: 'paragraph', text: 'His father understood the dream\'s significance and warned him not to tell his brothers, fearing their jealousy. However, his brothers were already envious and plotted against him.' },
      { type: 'paragraph', text: 'They threw him into a well and told their father a wolf had eaten him. Yusuf (AS) was rescued by a caravan and sold as a slave in Egypt.' },
      { type: 'image', url: '/assets/images/stories/prophet-yusuf-trials-content-1.png', alt: 'Yusuf sold into slavery in Egypt', aiHint: 'boy caravan egypt market' },
      { type: 'paragraph', text: 'In Egypt, he faced further trials, including false accusations that led to his imprisonment. Even in prison, he remained steadfast in his faith and interpreted dreams for his fellow prisoners.'},
      { type: 'decision', prompt: 'Yusuf (AS) is in prison. How does he maintain his faith?', choices: [
        { text: 'He despairs and loses hope', nextNodeIndex: 6 },
        { text: 'He remains patient and trusts Allah', nextNodeIndex: 5 },
      ]},
      { type: 'paragraph', text: 'Through his ability to interpret the King\'s dream, Yusuf (AS) was released from prison and appointed to a high position, in charge of Egypt\'s storehouses during a time of famine.' },
      { type: 'paragraph', text: 'Years later, his brothers came to Egypt seeking grain. Yusuf (AS) recognized them, but they did not recognize him. Eventually, he revealed himself and forgave them for what they had done.' },
      { type: 'image', url: '/assets/images/stories/prophet-yusuf-trials-content-2.png', alt: 'Yusuf reunites with his family', aiHint: 'family reunion joy egypt' },
      { type: 'paragraph', text: 'His parents and brothers came to Egypt, and his dream was fulfilled when they prostrated to him out of respect. Yusuf (AS)\'s story is a beautiful example of patience, forgiveness, chastity, and the ultimate triumph of good over evil through Allah\'s divine plan.' },
    ],
  },
  {
    id: 'prophet-musa-pharaoh',
    title: 'Prophet Musa (AS) and Pharaoh',
    description: 'The epic struggle of Prophet Musa (Moses) against the tyrannical Pharaoh of Egypt.',
    moral: 'Truth will always prevail over falsehood, and Allah supports His messengers against oppressors.',
    thumbnailUrl: '/assets/images/stories/prophet-musa-pharaoh-thumbnail.png',
    imageAiHint: 'staff sea parting egypt',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Prophet Musa (AS) was born during a time when Pharaoh, the king of Egypt, was oppressing the Children of Israel and ordering the killing of their newborn sons.' },
      { type: 'image', url: '/assets/images/stories/prophet-musa-pharaoh-content-0.png', alt: 'Baby Musa in a basket on the Nile', aiHint: 'baby basket river egypt' },
      { type: 'paragraph', text: 'By Allah\'s command, Musa\'s mother placed him in a basket on the River Nile, and he was found and raised in Pharaoh\'s own household. Later, Allah spoke to Musa (AS) at Mount Tur and appointed him as a Prophet.' },
      { type: 'paragraph', text: 'Musa (AS) and his brother Harun (Aaron AS) went to Pharaoh, calling him to worship Allah and release the Children of Israel. Pharaoh arrogantly refused and challenged Musa (AS) to show a sign.' },
      { type: 'image', url: '/assets/images/stories/prophet-musa-pharaoh-content-1.png', alt: 'Musa confronting Pharaoh', aiHint: 'man staff king palace' },
      { type: 'paragraph', text: 'Musa (AS) performed miracles, like his staff turning into a serpent and his hand shining brightly. Pharaoh\'s magicians were defeated, and some of them believed in Allah.' },
      { type: 'decision', prompt: 'Pharaoh is furious after his magicians believe. What does he do?', choices: [
        { text: 'He repents and believes', nextNodeIndex: 7 },
        { text: 'He increases his tyranny', nextNodeIndex: 6 },
      ]},
      { type: 'paragraph', text: 'Despite numerous plagues sent by Allah as warnings, Pharaoh remained defiant. Finally, Musa (AS) led the Children of Israel out of Egypt.' },
      { type: 'paragraph', text: 'Pharaoh and his army pursued them to the Red Sea. Allah commanded Musa (AS) to strike the sea with his staff, and the sea parted, creating a dry path. The Children of Israel crossed safely.' },
      { type: 'image', url: '/assets/images/stories/prophet-musa-pharaoh-content-2.png', alt: 'Red Sea parting', aiHint: 'sea split path people' },
      { type: 'paragraph', text: 'When Pharaoh and his army tried to follow, the waters returned and drowned them all. This story shows Allah\'s power, His support for the oppressed, and the end of tyranny.' },
    ],
  },
  {
    id: 'prophet-isa-miracles',
    title: 'Prophet Isa (AS): Miracles and Message',
    description: 'The story of Prophet Isa (Jesus), his miraculous birth, his teachings, and his miracles.',
    moral: 'Allah is All-Powerful, able to perform any miracle. Follow the guidance of His prophets.',
    thumbnailUrl: '/assets/images/stories/prophet-isa-miracles-thumbnail.png',
    imageAiHint: 'man healing people light',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Prophet Isa (AS) was born miraculously to the Virgin Maryam (Mary AS) without a father, by the command of Allah.' },
      { type: 'image', url: '/assets/images/stories/prophet-isa-miracles-content-0.png', alt: 'Maryam with baby Isa', aiHint: 'mother baby halo divine' },
      { type: 'paragraph', text: 'As a baby in the cradle, he spoke to defend his mother\'s honor and declare his prophethood. He was given the Injeel (Gospel) and sent as a messenger to the Children of Israel.' },
      { type: 'paragraph', text: 'Allah granted Isa (AS) many miracles: he healed the sick, gave sight to the blind, cured lepers, and even brought the dead back to life, all by Allah\'s permission.' },
      { type: 'image', url: '/assets/images/stories/prophet-isa-miracles-content-1.png', alt: 'Isa performing a miracle', aiHint: 'man healing sick crowd' },
      { type: 'paragraph', text: 'He called his people to worship Allah alone and follow the true teachings. However, many disbelieved and plotted against him.' },
      { type: 'decision', prompt: 'What important message did Isa (AS) emphasize?', choices: [
        { text: 'Worshipping him as God', nextNodeIndex: 6 },
        { text: 'Worshipping Allah alone', nextNodeIndex: 5 },
      ]},
      { type: 'paragraph', text: 'Isa (AS) consistently taught the worship of One God, Allah, and corrected deviations from the true path. He also foretold the coming of Prophet Muhammad (PBUH).' },
      { type: 'paragraph', text: 'When his enemies tried to crucify him, Allah saved him and raised him up to heaven. Muslims believe Isa (AS) was not crucified but will return to Earth before the Day of Judgment.' },
      { type: 'paragraph', text: 'His life is a testament to Allah\'s power and a call to monotheism and righteous living.' },
    ],
  },
  {
    id: 'prophet-muhammad-first-revelation',
    title: 'Prophet Muhammad (PBUH): The First Revelation',
    description: 'The story of how Prophet Muhammad (PBUH) received the first verses of the Quran.',
    moral: 'The Quran is the word of Allah, revealed for the guidance of humanity. Seek knowledge.',
    thumbnailUrl: '/assets/images/stories/prophet-muhammad-first-revelation-thumbnail.png',
    imageAiHint: 'cave mountain light angel',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Muhammad (PBUH) was known for his honesty and contemplative nature. He would often retreat to the Cave of Hira near Makkah to meditate.' },
      { type: 'image', url: '/assets/images/stories/prophet-muhammad-first-revelation-content-0.png', alt: 'Cave of Hira', aiHint: 'mountain cave solitude' },
      { type: 'paragraph', text: 'One night during Ramadan, when he was about 40 years old, the Angel Jibril (Gabriel AS) appeared to him. The angel commanded him, "Iqra!" (Read/Recite!).' },
      { type: 'paragraph', text: 'Muhammad (PBUH), who was unlettered, replied, "I cannot read." The angel embraced him tightly and repeated the command twice more, receiving the same reply.' },
      { type: 'decision', prompt: 'The angel embraces him for the third time and then says:', choices: [
        { text: '"You are now a Prophet!"', nextNodeIndex: 5 },
        { text: 'The first verses of the Quran', nextNodeIndex: 4 },
      ]},
      { type: 'paragraph', text: 'Then, Angel Jibril (AS) recited the first verses of Surah Al-Alaq: "Read! In the name of your Lord who created - Created man from a clinging substance. Read! And your Lord is the Most Generous - Who taught by the pen - Taught man that which he knew not." (Quran 96:1-5).' },
      { type: 'image', url: '/assets/images/stories/prophet-muhammad-first-revelation-content-1.png', alt: 'Prophet Muhammad receiving revelation', aiHint: 'man light angel cave' },
      { type: 'paragraph', text: 'This powerful experience left Muhammad (PBUH) shaken. He hurried home to his wife Khadijah (RA), who comforted him and believed in his prophethood, becoming the first Muslim.' },
      { type: 'paragraph', text: 'This event marked the beginning of his prophethood and the revelation of the Quran, which continued for 23 years, guiding humanity to the truth.' },
    ],
  },
  {
    id: 'khadijah-support-prophet',
    title: 'Khadijah (RA): The First Believer',
    description: 'The story of Khadijah (RA), the Prophet Muhammad\'s (PBUH) beloved wife and his greatest supporter.',
    moral: 'Support for truth and righteousness, especially in difficult times, is invaluable.',
    thumbnailUrl: '/assets/images/stories/khadijah-support-prophet-thumbnail.png',
    imageAiHint: 'woman comforting man desert',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Khadijah bint Khuwaylid (RA) was a respected and successful businesswoman in Makkah. She recognized the noble character of Muhammad (PBUH) and proposed marriage to him, which he accepted.' },
      { type: 'image', url: '/assets/images/stories/khadijah-support-prophet-content-0.png', alt: 'Khadijah and Prophet Muhammad', aiHint: 'couple arabian historical' },
      { type: 'paragraph', text: 'When Prophet Muhammad (PBUH) received the first revelation in the Cave of Hira and returned home frightened and trembling, Khadijah (RA) was his source of comfort and strength.' },
      { type: 'paragraph', text: 'She listened to his experience and, without hesitation, believed in him and his message. She said, "Allah would never forsake you. You uphold kinship, help the needy, support the weak, honor your guests, and bear the truth."' },
      { type: 'decision', prompt: 'How did Khadijah (RA) support the Prophet (PBUH) in the early days of Islam?', choices: [
        { text: 'Only with words of comfort', nextNodeIndex: 5 },
        { text: 'With her wealth, emotional support, and belief', nextNodeIndex: 4 },
      ]},
      { type: 'paragraph', text: 'Khadijah (RA) was the first person to embrace Islam. She dedicated her wealth, her wisdom, and her entire being to supporting the Prophet (PBUH) and the nascent Muslim community during the challenging early years of persecution in Makkah.' },
      { type: 'image', url: '/assets/images/stories/khadijah-support-prophet-content-1.png', alt: 'Khadijah supporting the early Muslims', aiHint: 'woman community support historical' },
      { type: 'paragraph', text: 'She remained his most beloved wife and a pillar of support until her death. The Prophet (PBUH) always remembered her with love and respect. Her story teaches us about faith, loyalty, courage, and the immense role women played in Islam.' },
    ],
  },
   {
    id: 'abu-bakr-as-siddiq',
    title: 'Abu Bakr As-Siddiq (RA): The Truthful Companion',
    description: 'Learn about Abu Bakr (RA), the Prophet\'s closest companion and the first Caliph.',
    moral: 'Unwavering faith, immediate acceptance of truth, and steadfast support for righteousness are marks of a true believer.',
    thumbnailUrl: '/assets/images/stories/abu-bakr-as-siddiq-thumbnail.png',
    imageAiHint: 'two men desert journey',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Abu Bakr (RA) was a close friend of Prophet Muhammad (PBUH) even before Islam. When the Prophet (PBUH) first told him about his prophethood, Abu Bakr (RA) believed immediately without any hesitation, earning him the title "As-Siddiq" (The Truthful).' },
      { type: 'image', url: '/assets/images/stories/abu-bakr-as-siddiq-content-0.png', alt: 'Abu Bakr with Prophet Muhammad', aiHint: 'men friends arabian historical' },
      { type: 'paragraph', text: 'He dedicated his life and wealth to Islam. He freed many Muslim slaves who were being persecuted, including Bilal (RA).' },
      { type: 'paragraph', text: 'Abu Bakr (RA) was the Prophet\'s companion during the dangerous Hijrah (migration) from Makkah to Madinah, hiding with him in the Cave of Thawr. The Quran mentions this, saying, "...the second of two, when they were in the cave and he said to his companion, \'Do not grieve; indeed Allah is with us.\'" (Quran 9:40).' },
      { type: 'image', url: '/assets/images/stories/abu-bakr-as-siddiq-content-1.png', alt: 'Inside Cave Thawr', aiHint: 'men cave talking' },
      { type: 'decision', prompt: 'After the Prophet\'s (PBUH) death, what major role did Abu Bakr (RA) play?', choices: [
        { text: 'He retired from public life', nextNodeIndex: 6 },
        { text: 'He became the first Caliph', nextNodeIndex: 5 },
      ]},
      { type: 'paragraph', text: 'After the Prophet Muhammad (PBUH) passed away, Abu Bakr (RA) was chosen as the first Caliph (successor). He led the Muslim community with wisdom and firmness, especially during challenging times like the Wars of Apostasy.' },
      { type: 'paragraph', text: 'He also played a crucial role in the compilation of the Quran into a single book. His life is an example of profound faith, loyalty, generosity, and leadership.' },
    ],
  },
  {
    id: 'umar-ibn-al-khattab',
    title: 'Umar ibn Al-Khattab (RA): The Just Ruler',
    description: 'The story of Umar\'s (RA) conversion and his renowned justice as a Caliph.',
    moral: 'Truth can transform hearts. Justice and compassion are vital for leadership.',
    thumbnailUrl: '/assets/images/stories/umar-ibn-al-khattab-thumbnail.png',
    imageAiHint: 'man strong leader justice',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Umar ibn Al-Khattab (RA) was initially a strong opponent of Islam, known for his fierce temper and strength.' },
      { type: 'image', url: '/assets/images/stories/umar-ibn-al-khattab-content-0.png', alt: 'Umar before Islam', aiHint: 'strong warrior angry historical' },
      { type: 'paragraph', text: 'One day, intending to harm the Prophet (PBUH), he learned his own sister had embraced Islam. He went to her house in anger but was moved upon hearing verses of the Quran being recited (from Surah Taha).' },
      { type: 'paragraph', text: 'His heart softened, and he went to Prophet Muhammad (PBUH) and declared his faith. His conversion was a great boost to the Muslims, who could then pray openly at the Kaaba.' },
      { type: 'decision', prompt: 'What was Umar (RA) famously known for as the second Caliph?', choices: [
        { text: 'His wealth and luxury', nextNodeIndex: 5 },
        { text: 'His justice and care for the people', nextNodeIndex: 4 },
      ]},
      { type: 'paragraph', text: 'As the second Caliph, Umar (RA) was known as "Al-Farooq" (The One Who Distinguishes Between Right and Wrong). His caliphate was marked by remarkable justice, expansion of the Muslim state, and establishment of many administrative systems.' },
      { type: 'image', url: '/assets/images/stories/umar-ibn-al-khattab-content-1.png', alt: 'Umar as Caliph helping the needy', aiHint: 'leader night checking poor' },
      { type: 'paragraph', text: 'He was known to walk the streets at night to check on the condition of his people. His life exemplifies courage, transformation through faith, and righteous leadership.' },
    ],
  },
  {
    id: 'bilal-ibn-rabah',
    title: 'Bilal ibn Rabah (RA): The Voice of Faith',
    description: 'The story of Bilal (RA), his steadfastness under torture, and becoming the first Muezzin.',
    moral: 'Faith in Allah gives strength against oppression. Piety, not race or status, determines honor in Islam.',
    thumbnailUrl: '/assets/images/stories/bilal-ibn-rabah-thumbnail.png',
    imageAiHint: 'man black calling prayer',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Bilal ibn Rabah (RA) was an Abyssinian slave in Makkah. When he embraced Islam, his master, Umayyah ibn Khalaf, subjected him to brutal torture to force him to renounce his faith.' },
      { type: 'image', url: '/assets/images/stories/bilal-ibn-rabah-content-0.png', alt: 'Bilal being tortured', aiHint: 'man desert torture rock' },
      { type: 'paragraph', text: 'He would be taken out during the hottest part of the day, a heavy rock placed on his chest, and ordered to reject Islam. Despite the agony, Bilal (RA) would only repeat, "Ahad, Ahad" (Allah is One, One).' },
      { type: 'decision', prompt: 'Who came to Bilal\'s (RA) rescue?', choices: [
        { text: 'His master had a change of heart', nextNodeIndex: 4 },
        { text: 'Abu Bakr As-Siddiq (RA)', nextNodeIndex: 3 },
      ]},
      { type: 'paragraph', text: 'Abu Bakr As-Siddiq (RA) bought Bilal (RA) from his cruel master and set him free. Bilal (RA) became a close companion of the Prophet Muhammad (PBUH).' },
      { type: 'paragraph', text: 'After the migration to Madinah, when the Adhan (call to prayer) was established, Prophet Muhammad (PBUH) chose Bilal (RA) to be the first Muezzin (caller to prayer) due to his beautiful, powerful voice and strong faith.' },
      { type: 'image', url: '/assets/images/stories/bilal-ibn-rabah-content-1.png', alt: 'Bilal calling the Adhan from a high place', aiHint: 'man mosque calling prayer sunrise' },
      { type: 'paragraph', text: 'His voice resonated with the message of Tawhid. Bilal\'s story is a powerful testament to the strength of faith, the equality in Islam, and the honor found in devotion to Allah.' },
    ],
  },
  {
    id: 'prophet-yunus-and-the-whale',
    title: 'Prophet Yunus (AS) and the Whale',
    description: 'Learn about patience and repentance from the story of Prophet Yunus (Jonah).',
    moral: 'Always be patient and seek forgiveness from Allah. Never lose hope in His mercy.',
    thumbnailUrl: '/assets/images/stories/prophet-yunus-and-the-whale-thumbnail.png',
    imageAiHint: 'whale ocean prophet man',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Prophet Yunus (AS) was a messenger of Allah sent to the people of Nineveh. He called them to worship Allah alone, but they initially rejected his message.' },
      { type: 'image', url: '/assets/images/stories/prophet-yunus-and-the-whale-content-0.png', alt: 'Prophet Yunus preaching', aiHint: 'man preaching town historical' },
      { type: 'paragraph', text: 'Feeling frustrated by their persistent disbelief, Prophet Yunus (AS) left his people in anger, without waiting for Allah\'s permission. He boarded a ship.' },
      { type: 'paragraph', text: 'A great storm arose, and the ship was about to sink. The crew cast lots to throw someone overboard to lighten the load, and the lot fell on Yunus (AS) three times.' },
      { type: 'decision', prompt: 'What happened when Yunus (AS) was cast into the sea?', choices: [
        { text: 'He drowned in the storm', nextNodeIndex: 6 },
        { text: 'A giant whale swallowed him by Allah\'s command', nextNodeIndex: 5 },
      ]},
      { type: 'paragraph', text: 'By Allah\'s command, a giant whale swallowed him. Inside the dark belly of the whale, Prophet Yunus (AS) realized his mistake and repented sincerely.' },
      { type: 'image', url: '/assets/images/stories/prophet-yunus-and-the-whale-content-1.png', alt: 'Whale swallowing Prophet Yunus', aiHint: 'whale sea storm man' },
      { type: 'paragraph', text: 'He prayed: "La ilaha illa Anta, Subhanaka, inni kuntu minaz-zalimin" (There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers). (Quran 21:87)' },
      { type: 'paragraph', text: 'Allah, the Most Merciful, accepted his repentance and commanded the whale to cast Prophet Yunus (AS) onto the shore. He was weak but safe.' },
      { type: 'paragraph', text: 'Allah then caused a plant to grow, providing him with food and shelter. Prophet Yunus (AS) returned to his people of Nineveh, and to his surprise, he found that they had repented and believed in Allah during his absence. They were forgiven and blessed.' },
      { type: 'paragraph', text: 'This story teaches us the importance of patience (especially in Dawah), seeking Allah\'s permission, the power of sincere repentance, and that Allah\'s mercy encompasses all things.' },
    ],
  },
  {
    id: 'the-honest-shepherd',
    title: 'The Honest Shepherd Boy',
    description: 'A tale about the importance of honesty, even when no one is watching.',
    moral: 'Honesty is a virtue that pleases Allah and earns trust. Allah is always watching.',
    thumbnailUrl: '/assets/images/stories/the-honest-shepherd-thumbnail.png',
    imageAiHint: 'shepherd sheep hills boy',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Once, there was a young shepherd boy who looked after a flock of sheep for a wealthy man in the hills.' },
      { type: 'image', url: '/assets/images/stories/the-honest-shepherd-content-0.png', alt: 'Shepherd boy with sheep on a hill', aiHint: 'boy sheep field green' },
      { type: 'paragraph', text: 'One day, a group of travelers, including Abdullah ibn Umar (RA), a companion of the Prophet (PBUH), passed by. They were testing the boy\'s honesty. They offered to buy a sheep from him.' },
      { type: 'paragraph', text: 'The boy politely refused, saying, "These sheep are not mine to sell. I am only entrusted by their owner to care for them."' },
      { type: 'decision', prompt: 'The travelers then suggested:', choices: [
        { text: '"Sell us one, and tell your master a wolf ate it. You can keep the money."', nextNodeIndex: 4 },
        { text: '"Just give us one, your master won\'t know."', nextNodeIndex: 4 },
      ]},
      { type: 'paragraph', text: 'The boy, with strong faith, replied, "My master may not see me, but where is Allah? Allah sees everything."' },
      { type: 'image', url: '/assets/images/stories/the-honest-shepherd-content-1.png', alt: 'Boy pointing to the sky', aiHint: 'boy nature sky faith' },
      { type: 'paragraph', text: 'Abdullah ibn Umar (RA) was deeply impressed by the boy\'s honesty and fear of Allah. He later found the boy\'s master, purchased the boy and the sheep, and then set the boy free and gifted him the sheep as a reward for his honesty.' },
      { type: 'paragraph', text: 'This story teaches us that true honesty is being truthful and trustworthy even when no one is watching, because Allah is All-Seeing and All-Knowing.' },
    ],
  },
  {
    id: 'kindness-to-animals',
    title: 'Kindness to Animals in Islam',
    description: 'Discover how Islam teaches us to be kind to all creatures great and small.',
    moral: 'Being kind to animals is a vital part of Islamic teachings and brings great reward.',
    thumbnailUrl: '/assets/images/stories/kindness-to-animals-thumbnail.png',
    imageAiHint: 'child cat animals care',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Islam places great emphasis on compassion and mercy towards all living beings, including animals. Prophet Muhammad (peace be upon him) set many examples and taught his followers to treat animals with kindness and respect.' },
      { type: 'image', url: '/assets/images/stories/kindness-to-animals-content-0.png', alt: 'Person feeding a cat', aiHint: 'hand feeding kitten outdoor' },
      { type: 'paragraph', text: 'There is a famous Hadith (saying of the Prophet PBUH) about a woman who was forgiven her sins by Allah because she showed mercy to a thirsty dog. She found a dog panting from thirst near a well, so she used her shoe to draw water from the well and gave it to the dog to drink.' },
      { type: 'decision', prompt: 'What does this act of kindness show?', choices: [
        { text: 'It was a small, insignificant act.', nextNodeIndex: 4 },
        { text: 'Even a simple act of mercy towards an animal can earn Allah\'s forgiveness.', nextNodeIndex: 3 },
      ]},
      { type: 'paragraph', text: 'This simple act of mercy earned her Paradise. Conversely, another Hadith tells of a woman who was punished in Hellfire for mistreating a cat. She had imprisoned it, neither feeding it nor allowing it to find its own food, until it died of hunger.' },
      { type: 'image', url: '/assets/images/stories/kindness-to-animals-content-1.png', alt: 'Children gently playing with a rabbit', aiHint: 'kids rabbit park gentle' },
      { type: 'paragraph', text: 'From these teachings, we learn that we should provide adequate food, water, and shelter for animals under our care. We must not overburden them, cause them unnecessary harm or distress, or use them for cruel sports.' },
      { type: 'paragraph', text: 'Even when slaughtering animals for food, Islam prescribes a humane method that minimizes suffering. Kindness to animals is a reflection of a Muslim\'s good character and understanding of their role as caretakers on Earth.' },
    ],
  },
  {
    id: 'value-of-salam',
    title: 'The Value of Spreading Salam',
    description: 'Learn the importance and blessings of the Islamic greeting "Assalamu Alaikum".',
    moral: 'Spread peace and kindness by greeting others with "Assalamu Alaikum" (Peace be upon you).',
    thumbnailUrl: '/assets/images/stories/value-of-salam-thumbnail.png',
    imageAiHint: 'kids greeting smile wave',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: '"Assalamu Alaikum" means "Peace be upon you". It\'s a beautiful and powerful greeting in Islam.' },
      { type: 'image', url: '/assets/images/stories/value-of-salam-content-0.png', alt: 'Diverse children smiling and waving', aiHint: 'children diverse happy greeting' },
      { type: 'paragraph', text: 'Prophet Muhammad (PBUH) emphasized its importance, teaching us to say Salam to people we know and even those we don\'t. It is a way to spread peace, love, and friendship among people.' },
      { type: 'paragraph', text: 'Responding to the Salam is also very important. If someone greets you with "Assalamu Alaikum," you should reply with "Wa Alaikum Assalam" (And upon you be peace), or an even better greeting like "Wa Alaikum Assalam wa Rahmatullahi" (And upon you be peace and the mercy of Allah).' },
      { type: 'decision', prompt: 'What is one of the benefits of spreading Salam?', choices: [
        { text: 'It makes you seem important.', nextNodeIndex: 5 },
        { text: 'It increases love between people and is a characteristic of believers.', nextNodeIndex: 4 },
      ]},
      { type: 'paragraph', text: 'The Prophet (PBUH) said that spreading Salam is one of the actions that will lead to Jannah (Paradise). It fosters a sense of community and goodwill.' },
      { type: 'image', url: '/assets/images/stories/value-of-salam-content-1.png', alt: 'Hands shaking in friendship', aiHint: 'hands shake peace community' },
      { type: 'paragraph', text: 'So, always try to be the first to greet others with Salam, and respond warmly when greeted. It\'s a simple act with great rewards from Allah.' },
    ],
  },
  {
    id: 'sharing-is-caring',
    title: 'Sharing is Caring: The Joy of Giving',
    description: 'A story about the joy and reward of sharing with others in Islam.',
    moral: 'Sharing brings happiness to others, blessings to ourselves, and is beloved by Allah.',
    thumbnailUrl: '/assets/images/stories/sharing-is-caring-thumbnail.png',
    imageAiHint: 'kids sharing toys food',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Little Omar had a big, juicy apple that his mother gave him. His friend Ali was looking at it with wishing eyes, as Ali didn\'t have one.' },
      { type: 'image', url: '/assets/images/stories/sharing-is-caring-content-0.png', alt: 'Boy with an apple, another boy looking', aiHint: 'boy apple friend watching' },
      { type: 'paragraph', text: 'Omar remembered what his teacher taught him: Prophet Muhammad (PBUH) said, "None of you truly believes until he loves for his brother what he loves for himself."' },
      { type: 'decision', prompt: 'What should Omar do with his apple?', choices: [
        { text: 'Eat the whole apple himself quickly', nextNodeIndex: 4 },
        { text: 'Offer to share the apple with Ali', nextNodeIndex: 5 },
      ]},
      { type: 'paragraph', text: 'If Omar eats it all himself, Ali might feel sad, and Omar would miss a chance to do a good deed. (This path can lead to a lesson on empathy and missed opportunity for reward)' },
      { type: 'paragraph', text: 'Omar decided to cut his apple in half and share it with Ali. Ali\'s face lit up with a big smile! They both enjoyed the sweet apple together, and their friendship grew stronger.' },
      { type: 'image', url: '/assets/images/stories/sharing-is-caring-content-1.png', alt: 'Two boys happily sharing an apple', aiHint: 'kids sharing fruit happy' },
      { type: 'paragraph', text: 'Sharing not only made Ali happy but also made Omar feel wonderful inside. Allah loves those who are generous and share what they have with others, whether it\'s food, toys, or even a smile.' },
    ],
  }
];
