import type { Story } from '@/lib/types';

export const dummyStories: Story[] = [
  {
    id: 'prophet-yunus-and-the-whale',
    title: 'Prophet Yunus (AS) and the Whale',
    description: 'Learn about patience and repentance from the story of Prophet Yunus (AS).',
    moral: 'Always be patient and seek forgiveness from Allah.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'whale ocean prophet',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Prophet Yunus (Jonah) was a messenger of Allah sent to the people of Nineveh. He called them to worship Allah alone, but they initially rejected his message.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Prophet Yunus preaching', aiHint: 'man preaching town' },
      { type: 'paragraph', text: 'Feeling frustrated, Prophet Yunus left his people without Allah\'s permission. He boarded a ship, but a great storm arose.' },
      { type: 'paragraph', text: 'To save the ship, the crew decided to cast one person overboard, and the lot fell on Yunus (AS). He was swallowed by a giant whale.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Whale swallowing Prophet Yunus', aiHint: 'whale sea storm' },
      { type: 'paragraph', text: 'Inside the whale\'s belly, in darkness, Prophet Yunus realized his mistake and prayed to Allah: "La ilaha illa Anta, Subhanaka, inni kuntu minaz-zalimin" (There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers).' },
      { type: 'paragraph', text: 'Allah, in His mercy, commanded the whale to cast Prophet Yunus onto the shore. He was weak but safe.' },
      { type: 'decision', prompt: 'What should Prophet Yunus do next?', choices: [
        { text: 'Rest and recover', nextNodeIndex: 8 },
        { text: 'Return to his people', nextNodeIndex: 8 },
      ]},
      { type: 'paragraph', text: 'Allah then caused a plant to grow, providing him with food and shelter. Prophet Yunus (AS) returned to his people, who had repented and believed in Allah. They were forgiven and blessed.' },
      { type: 'paragraph', text: 'This story teaches us the importance of patience, seeking Allah\'s forgiveness, and never losing hope in His mercy.' },
    ],
  },
  {
    id: 'the-honest-shepherd',
    title: 'The Honest Shepherd Boy',
    description: 'A tale about the importance of honesty, even when no one is watching.',
    moral: 'Honesty is a virtue that pleases Allah and earns trust.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'shepherd sheep hills',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Once, there was a young shepherd boy who looked after a flock of sheep for a wealthy man.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Shepherd boy with sheep', aiHint: 'boy sheep field' },
      { type: 'paragraph', text: 'One day, a traveler passed by and offered to buy a sheep. The boy refused, saying, "These sheep are not mine. I am only entrusted to care for them."' },
      { type: 'paragraph', text: 'The traveler, testing him, said, "You can tell your master a wolf ate one." But the boy replied, "My master may not see me, but Allah sees me."' },
      { type: 'paragraph', text: 'The traveler was impressed by the boy\'s honesty. This story teaches us that true honesty is being truthful even when no one is looking, because Allah is always watching.' },
    ],
  },
  {
    id: 'kindness-to-animals',
    title: 'Kindness to Animals in Islam',
    description: 'Discover how Islam teaches us to be kind to all creatures.',
    moral: 'Being kind to animals is an important part of Islamic teachings.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'child cat animals',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Islam emphasizes compassion and mercy towards all living beings, including animals. The Prophet Muhammad (peace be upon him) taught his followers to treat animals with kindness and respect.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Person feeding a cat', aiHint: 'hand feeding kitten' },
      { type: 'paragraph', text: 'There is a famous Hadith about a woman who was forgiven her sins because she gave water to a thirsty dog. This shows the great reward for being kind to animals.' },
      { type: 'paragraph', text: 'Conversely, another Hadith tells of a woman who was punished for mistreating a cat by imprisoning it without food or water.' },
      { type: 'paragraph', text: 'We should provide food and water for animals under our care, not overburden them, and avoid causing them any harm or distress.' },
    ],
  },
  {
    id: 'prophet-adam-creation',
    title: 'The Story of Prophet Adam (AS)',
    description: 'Learn about the creation of the first man, Prophet Adam (AS).',
    moral: 'Obey Allah and seek forgiveness when you make a mistake.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'garden paradise firstman',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Allah created Prophet Adam (AS) from clay and breathed life into him. He taught Adam the names of all things.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Allah creating Adam', aiHint: 'light hands clay' },
      { type: 'paragraph', text: 'Adam (AS) and Hawa (Eve) lived peacefully in Jannah (Paradise). Allah allowed them to enjoy everything except the fruit of one specific tree.' },
      { type: 'paragraph', text: 'Shaytan (Satan) tricked them into eating from the forbidden tree. They disobeyed Allah.'},
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Forbidden fruit', aiHint: 'glowing fruit tree' },
      { type: 'paragraph', text: 'Adam (AS) and Hawa (Eve) immediately felt regret and asked Allah for forgiveness. Allah, The Most Merciful, forgave them but sent them to live on Earth as a test.'},
      { type: 'paragraph', text: 'This story teaches us about obedience, repentance, and Allah\'s vast mercy.' },
    ],
  },
  {
    id: 'prophet-nuh-ark',
    title: 'Prophet Nuh (AS) and the Ark',
    description: 'The story of Prophet Nuh (Noah) and the great flood.',
    moral: 'Trust in Allah\'s plan and persevere in doing good.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'ark animals flood',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Prophet Nuh (AS) preached to his people for many years, but most of them refused to believe.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Nuh preaching', aiHint: 'oldman speaking crowd' },
      { type: 'paragraph', text: 'Allah commanded Nuh (AS) to build a huge ark. People mocked him, but he continued his work with faith.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Nuh building ark', aiHint: 'man building boat' },
      { type: 'paragraph', text: 'When the ark was ready, Allah told Nuh (AS) to take pairs of every animal and the believers with him.' },
      { type: 'paragraph', text: 'Then, a great flood covered the land, and only those on the ark were saved. This story shows Allah\'s power and justice.' },
    ],
  },
  {
    id: 'prophet-ibrahim-fire',
    title: 'Prophet Ibrahim (AS) and the Fire',
    description: 'The miracle of Prophet Ibrahim (Abraham) being saved from the fire.',
    moral: 'Have unwavering faith in Allah, even in the face of great danger.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'fire miracle prophet',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Prophet Ibrahim (AS) called his people to worship Allah alone and stop worshipping idols.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Ibrahim and idols', aiHint: 'man idols stone' },
      { type: 'paragraph', text: 'The king and his people became angry and decided to throw Ibrahim (AS) into a huge fire.' },
      { type: 'paragraph', text: 'But Allah commanded the fire: "O fire, be coolness and safety upon Ibrahim." The fire did not harm him at all.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Ibrahim safe in fire', aiHint: 'man fire unharmed' },
      { type: 'paragraph', text: 'This miracle showed Allah\'s power and protected His prophet. It teaches us to stand for truth and trust Allah completely.' },
    ],
  },
  {
    id: 'prophet-musa-red-sea',
    title: 'Prophet Musa (AS) and the Red Sea',
    description: 'How Prophet Musa (Moses) led his people across the Red Sea.',
    moral: 'Allah can make a way where there seems to be no way.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'sea parting prophet',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Pharaoh and his army chased Prophet Musa (AS) and the Children of Israel to the edge of the Red Sea.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'People by the sea', aiHint: 'crowd sea escape' },
      { type: 'paragraph', text: 'With the sea in front and the enemy behind, the people felt trapped. But Musa (AS) had faith in Allah.' },
      { type: 'paragraph', text: 'Allah commanded Musa (AS) to strike the sea with his staff. The sea parted, creating a dry path for them to cross.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Sea parting', aiHint: 'ocean split path' },
      { type: 'paragraph', text: 'After they crossed safely, the sea closed in on Pharaoh and his army, drowning them. This story shows Allah\'s ultimate power and protection for believers.' },
    ],
  },
  {
    id: 'prophet-muhammad-cave',
    title: 'Prophet Muhammad (PBUH) in Cave Thawr',
    description: 'The story of Hijrah and protection in the cave.',
    moral: 'Allah protects those who trust in Him.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'cave spiderweb birdnest',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'When Prophet Muhammad (PBUH) and Abu Bakr (RA) were migrating to Madinah (Hijrah), they hid in Cave Thawr.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Cave entrance', aiHint: 'mountain cave entrance' },
      { type: 'paragraph', text: 'Their enemies were searching for them and came very close to the cave entrance.' },
      { type: 'paragraph', text: 'By Allah\'s command, a spider spun a web across the cave mouth, and a dove laid eggs, making it seem undisturbed.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Spiderweb on cave', aiHint: 'spiderweb bird cave' },
      { type: 'paragraph', text: 'The searchers saw this and thought no one could be inside, so they left. Allah protected His Prophet and his companion.' },
    ],
  },
  {
    id: 'the-boy-and-the-king',
    title: 'The Boy and the King (Ashab al-Ukhdud)',
    description: 'A story of faith and perseverance against a tyrannical king.',
    moral: 'True faith can move mountains and inspire others, even in death.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'boy king faith',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'A young boy learned about true faith from a believer, despite the king\'s magician trying to teach him magic.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Boy learning', aiHint: 'boy oldman teaching' },
      { type: 'paragraph', text: 'The boy performed miracles in Allah\'s name, and many people started to believe.' },
      { type: 'paragraph', text: 'The king became furious and tried to kill the boy multiple times, but failed. The boy told the king he could only be killed if he shot an arrow in Allah\'s name.' },
      { type: 'paragraph', text: 'The king did so, and the boy died. Seeing this, many more people declared their faith, leading the king to persecute them.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'People by fire trench', aiHint: 'crowd fire faith' },
      { type: 'paragraph', text: 'This story highlights ultimate trust in Allah and the power of sincere faith.' },
    ],
  },
  {
    id: 'the-value-of-salam',
    title: 'The Value of Saying Salam',
    description: 'Learn the importance and blessings of the Islamic greeting.',
    moral: 'Spread peace and kindness by greeting others with "Assalamu Alaikum".',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'kids greeting smile',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: '"Assalamu Alaikum" means "Peace be upon you". It\'s a beautiful greeting in Islam.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Children greeting', aiHint: 'children waving smile' },
      { type: 'paragraph', text: 'Prophet Muhammad (PBUH) taught us to say Salam to people we know and even those we don\'t know.' },
      { type: 'paragraph', text: 'Saying Salam spreads love, friendship, and earns rewards from Allah.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Hands shaking', aiHint: 'hands shake peace' },
      { type: 'paragraph', text: 'When someone greets you with Salam, you should reply with "Wa Alaikum Assalam" (And upon you be peace) or something even better.' },
    ],
  },
  {
    id: 'sharing-is-caring',
    title: 'Sharing is Caring',
    description: 'A story about the joy and reward of sharing with others.',
    moral: 'Sharing brings happiness to others and blessings to ourselves.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'kids sharing toys',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Little Aisha had a box of colorful crayons. Her friend Fatima didn\'t have any.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Girl with crayons', aiHint: 'girl crayons art' },
      { type: 'paragraph', text: 'Aisha remembered her mother taught her that sharing is a good deed in Islam.' },
      { type: 'decision', prompt: 'What should Aisha do?', choices: [
        { text: 'Keep all crayons to herself', nextNodeIndex: 4 },
        { text: 'Share some crayons with Fatima', nextNodeIndex: 5 },
      ]},
      { type: 'paragraph', text: 'If Aisha keeps them, Fatima might feel sad. (This path can lead to a lesson on empathy)' },
      { type: 'paragraph', text: 'Aisha decided to share her crayons with Fatima. They both drew beautiful pictures together and had so much fun! Sharing made them both happy.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Girls drawing together', aiHint: 'kids drawing happy' },
      { type: 'paragraph', text: 'Allah loves those who are generous and share with others.' },
    ],
  },
  // Add 38 more stories
  {
    id: 'prophet-yusuf-dream',
    title: 'Prophet Yusuf (AS) and His Dream',
    description: 'The story of Prophet Yusuf (Joseph) and his famous dream.',
    moral: 'Patience and trust in Allah lead to a good outcome.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'boy stars dream',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Young Yusuf (AS) had a dream where eleven stars, the sun, and the moon were prostrating to him.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Yusuf dreaming', aiHint: 'boy sleeping dream' },
      { type: 'paragraph', text: 'His father, Prophet Yaqub (Jacob AS), advised him not to tell his brothers, as they might become jealous.' },
      { type: 'paragraph', text: 'This story unfolds with trials, patience, and eventual fulfillment of the dream, showing Allah\'s plan.' },
    ],
  },
  {
    id: 'elephant-army-kaaba',
    title: 'The Army of Elephants (Ashab al-Fil)',
    description: 'The story of Abraha\'s attempt to destroy the Kaaba.',
    moral: 'Allah protects His sacred house.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'kaaba elephants birds',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Abraha, a Yemeni ruler, tried to destroy the Kaaba with an army of elephants.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Elephants marching', aiHint: 'elephants army ancient' },
      { type: 'paragraph', text: 'As they approached Mecca, Allah sent flocks of birds that dropped small stones on the army, destroying them.' },
      { type: 'paragraph', text: 'This event, happening in the year of Prophet Muhammad\'s (PBUH) birth, showed Allah\'s protection over the Kaaba.' },
    ],
  },
  {
    id: 'prophet-dawud-goliath',
    title: 'Prophet Dawud (AS) and Goliath',
    description: 'The young shepherd Dawud (David) defeats the giant Goliath.',
    moral: 'Courage and faith in Allah can overcome any obstacle.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'boy giant battle',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'The giant warrior Goliath challenged the army of Israel, and everyone was afraid.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Goliath the giant', aiHint: 'giant warrior scary' },
      { type: 'paragraph', text: 'Young Dawud (AS), a shepherd, stepped forward with faith in Allah and a simple slingshot.' },
      { type: 'paragraph', text: 'He defeated Goliath with a single stone, becoming a hero and later a great prophet and king.' },
    ],
  },
  {
    id: 'prophet-sulaiman-ant',
    title: 'Prophet Sulaiman (AS) and the Ant',
    description: 'Prophet Sulaiman (Solomon) understands the speech of an ant.',
    moral: 'Be humble and attentive to even the smallest of Allah\'s creatures.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'king ant tiny',
    ageGroup: '4-8',
    content: [
      { type: 'paragraph', text: 'Prophet Sulaiman (AS) was given the ability to understand the speech of animals.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Sulaiman with animals', aiHint: 'king animals talking' },
      { type: 'paragraph', text: 'Once, he overheard an ant warning other ants to enter their dwellings so Sulaiman\'s army wouldn\'t crush them.' },
      { type: 'paragraph', text: 'Sulaiman (AS) smiled, impressed by the ant\'s wisdom and concern, and thanked Allah for his blessings.' },
    ],
  },
  {
    id: 'maryam-birth-isa',
    title: 'Maryam (AS) and the Birth of Isa (AS)',
    description: 'The miraculous birth of Prophet Isa (Jesus) to Maryam (Mary).',
    moral: 'Allah\'s power is limitless; He can create whatever He wills.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'mother baby light',
    ageGroup: '9-16',
    content: [
      { type: 'paragraph', text: 'Maryam (AS) was a pure and devout woman. An angel appeared to her with news of a son.' },
      { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Angel appearing to Maryam', aiHint: 'woman angel divine' },
      { type: 'paragraph', text: 'She miraculously conceived Prophet Isa (AS) without a father, a sign of Allah\'s great power.' },
      { type: 'paragraph', text: 'The story highlights her faith and the special status of Prophet Isa (AS).' },
    ],
  },
  // Adding 33 more stories to reach ~50
  {
    id: 'bilal-call-to-prayer',
    title: 'Bilal (RA) and the First Adhan',
    description: 'The story of Bilal ibn Rabah (RA) and his beautiful call to prayer.',
    moral: 'Faith and devotion are valued by Allah, regardless of status or origin.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'man calling prayer',
    ageGroup: '4-8',
    content: [ { type: 'paragraph', text: 'Bilal (RA), a former slave, was chosen for his beautiful voice to be the first Muezzin (caller to prayer) in Islam.' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Bilal calling Adhan', aiHint: 'man silhouette mosque' }, { type: 'paragraph', text: 'His story shows the equality in Islam and the honor of calling people to worship Allah.' } ],
  },
  {
    id: 'spider-cave-hijrah',
    title: 'The Spider and the Dove',
    description: 'How Allah used small creatures to protect Prophet Muhammad (PBUH) during Hijrah.',
    moral: 'Allah can use any means to protect those He wills.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'cave spiderweb dove',
    ageGroup: '4-8',
    content: [ { type: 'paragraph', text: 'During the Hijrah (migration), Prophet Muhammad (PBUH) and Abu Bakr (RA) hid in Cave Thawr.' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Cave with spiderweb', aiHint: 'cave opening nature' }, { type: 'paragraph', text: 'A spider spun a web and a dove nested at the entrance, convincing pursuers no one was inside.' } ],
  },
  {
    id: 'golden-calf-musa',
    title: 'Prophet Musa (AS) and the Golden Calf',
    description: 'The story of the Israelites worshipping a golden calf while Musa (AS) was away.',
    moral: 'Stay firm on Tawhid (Oneness of Allah) and avoid shirk (polytheism).',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'golden calf people',
    ageGroup: '9-16',
    content: [ { type: 'paragraph', text: 'While Prophet Musa (AS) was on Mount Sinai receiving the Torah, some Israelites were misled into worshipping a golden calf.' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'People around golden calf', aiHint: 'idol worship ancient' }, { type: 'paragraph', text: 'This story warns against idol worship and emphasizes the importance of monotheism.' } ],
  },
  {
    id: 'splitting-moon-miracle',
    title: 'The Splitting of the Moon',
    description: 'A miracle performed by Prophet Muhammad (PBUH) as a sign for the disbelievers.',
    moral: 'Allah grants His prophets signs to prove their truthfulness.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'moon split sky',
    ageGroup: '9-16',
    content: [ { type: 'paragraph', text: 'The disbelievers in Mecca asked Prophet Muhammad (PBUH) for a miracle.' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Moon in the sky', aiHint: 'night sky moon' }, { type: 'paragraph', text: 'By Allah\'s permission, he pointed to the moon, and it split into two halves.' } ],
  },
  {
    id: 'ismail-sacrifice-story',
    title: 'Prophet Ibrahim (AS) and Ismail (AS)',
    description: 'The ultimate test of faith: Ibrahim\'s willingness to sacrifice his son Ismail.',
    moral: 'True submission to Allah involves obedience even in the hardest trials.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'father son mountain',
    ageGroup: '9-16',
    content: [ { type: 'paragraph', text: 'Allah tested Prophet Ibrahim (AS) by commanding him to sacrifice his beloved son, Ismail (AS).' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Ibrahim and Ismail', aiHint: 'man boy desert' }, { type: 'paragraph', text: 'Both showed complete submission. Allah then ransomed Ismail (AS) with a ram. This is commemorated in Eid al-Adha.' } ],
  },
  {
    id: 'khidr-musa-journey',
    title: 'Prophet Musa (AS) and Al-Khidr',
    description: 'The journey of Musa (AS) with Al-Khidr, learning about divine wisdom.',
    moral: 'Allah\'s wisdom is vast, and events may have meanings beyond our immediate understanding.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'two men journey',
    ageGroup: '9-16',
    content: [ { type: 'paragraph', text: 'Prophet Musa (AS) traveled with Al-Khidr, a wise servant of Allah, to learn hidden knowledge.' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Men on a boat', aiHint: 'boat sea journey' }, { type: 'paragraph', text: 'Al-Khidr performed actions that seemed strange, but each had a deeper, wise purpose.' } ],
  },
  {
    id: 'treaty-hudaibiyah',
    title: 'The Treaty of Hudaibiyah',
    description: 'A pivotal treaty made by Prophet Muhammad (PBUH) that led to future victories.',
    moral: 'Patience and wise diplomacy can lead to greater good, even if terms seem unfavorable initially.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'writing treaty scroll',
    ageGroup: '9-16',
    content: [ { type: 'paragraph', text: 'Prophet Muhammad (PBUH) made a peace treaty with the Meccans at Hudaibiyah.' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'People signing treaty', aiHint: 'agreement signing historic' }, { type: 'paragraph', text: 'Though some terms seemed disadvantageous, it was a strategic victory that paved the way for the peaceful conquest of Mecca.' } ],
  },
  {
    id: 'umar-conversion-islam',
    title: 'Umar ibn Al-Khattab\'s (RA) Conversion',
    description: 'The powerful story of how Umar (RA), a strong opponent, embraced Islam.',
    moral: 'Allah guides whom He wills; hearts can change dramatically.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'strong man light',
    ageGroup: '9-16',
    content: [ { type: 'paragraph', text: 'Umar (RA) was initially a fierce enemy of Islam. He set out to harm the Prophet (PBUH).' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Man reading Quran', aiHint: 'man reading holybook' }, { type: 'paragraph', text: 'Hearing verses of the Quran, his heart was moved, and he converted, becoming a great supporter of Islam.' } ],
  },
  {
    id: 'night-journey-isra-miraj',
    title: 'Isra and Mi\'raj: The Night Journey',
    description: 'Prophet Muhammad\'s (PBUH) miraculous night journey and ascension to the heavens.',
    moral: 'Allah honors His prophets with extraordinary experiences and signs.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'winged horse sky',
    ageGroup: '9-16',
    content: [ { type: 'paragraph', text: 'Prophet Muhammad (PBUH) was taken on a miraculous journey from Mecca to Jerusalem (Isra) and then ascended through the heavens (Mi\'raj).' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Dome of the Rock', aiHint: 'jerusalem mosque night' }, { type: 'paragraph', text: 'During this journey, the five daily prayers were ordained.' } ],
  },
  {
    id: 'battle-badr-victory',
    title: 'The Battle of Badr',
    description: 'The first major battle in Islam, where a small Muslim army defeated a larger Meccan force.',
    moral: 'With Allah\'s help, even a small, righteous group can overcome great odds.',
    thumbnailUrl: 'https://placehold.co/300x200.png',
    imageAiHint: 'battle swords desert',
    ageGroup: '9-16',
    content: [ { type: 'paragraph', text: 'At Badr, the outnumbered Muslims, strong in faith, faced a larger, better-equipped Meccan army.' }, { type: 'image', url: 'https://placehold.co/600x400.png', alt: 'Warriors in battle', aiHint: 'ancient battle scene' }, { type: 'paragraph', text: 'Allah granted them a decisive victory, strengthening the early Muslim community.' } ],
  },
  { id: 'story-11', title: 'The Ant and the Grasshopper (Islamic version)', description: 'A story about preparing for the future.', moral: 'Work hard and prepare for times of need, trusting in Allah.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'ant grasshopper food', ageGroup: '4-8', content: [{type: 'paragraph', text: 'An ant worked hard all summer, while a grasshopper sang. Winter came...'}]},
  { id: 'story-12', title: 'The Boy Who Cried Wolf (Islamic version)', description: 'The consequences of lying.', moral: 'Lying destroys trust; always speak the truth.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'boy wolf village', ageGroup: '4-8', content: [{type: 'paragraph', text: 'A shepherd boy falsely cried "Wolf!" too many times...'}]},
  { id: 'story-13', title: 'Prophet Salih (AS) and the She-Camel', description: 'The people of Thamud and their test.', moral: 'Disobedience to Allah\'s signs brings punishment.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'camel rock mountain', ageGroup: '9-16', content: [{type: 'paragraph', text: 'Prophet Salih (AS) was sent to Thamud. Allah gave them a she-camel as a sign...'}]},
  { id: 'story-14', title: 'The Sleepers of the Cave (Ashab al-Kahf)', description: 'Young men who slept for centuries to protect their faith.', moral: 'Allah protects those who sincerely seek refuge in Him for their faith.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'cave sleeping men', ageGroup: '9-16', content: [{type: 'paragraph', text: 'A group of faithful youths fled persecution and took refuge in a cave...'}]},
  { id: 'story-15', title: 'Luqman\'s Advice to His Son', description: 'Wise counsel from Luqman the Wise.', moral: 'Listen to wise advice, especially regarding faith and good conduct.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'father son talking', ageGroup: '9-16', content: [{type: 'paragraph', text: 'Luqman (AS) gave his son valuable advice, starting with not associating partners with Allah...'}]},
  { id: 'story-16', title: 'The Generosity of Abu Bakr (RA)', description: 'An example of selfless giving.', moral: 'Be generous in the way of Allah.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'man giving charity', ageGroup: '4-8', content: [{type: 'paragraph', text: 'Abu Bakr (RA) was known for his immense generosity, often giving all he had for Islam.'}]},
  { id: 'story-17', title: 'Respecting Parents (Uways al-Qarani)', description: 'The story of Uways, who was devoted to his mother.', moral: 'Great blessings come from honoring and serving one\'s parents.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'man serving mother', ageGroup: '9-16', content: [{type: 'paragraph', text: 'Uways al-Qarani was praised by the Prophet (PBUH) for his exceptional devotion to his mother.'}]},
  { id: 'story-18', title: 'The Patience of Prophet Ayyub (AS)', description: 'Prophet Ayyub\'s (Job) unwavering patience through severe trials.', moral: 'Patience in hardship is a great virtue rewarded by Allah.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'man enduring hardship', ageGroup: '9-16', content: [{type: 'paragraph', text: 'Prophet Ayyub (AS) faced loss of wealth, family, and health, but remained patient and thankful.'}]},
  { id: 'story-19', title: 'Forgiveness at the Conquest of Mecca', description: 'Prophet Muhammad\'s (PBUH) mercy towards his former enemies.', moral: 'Forgiveness and mercy are superior to revenge.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'crowd leader mercy', ageGroup: '9-16', content: [{type: 'paragraph', text: 'When Prophet Muhammad (PBUH) conquered Mecca, he forgave those who had persecuted him.'}]},
  { id: 'story-20', title: 'The Importance of Seeking Knowledge', description: 'Islam encourages seeking knowledge.', moral: 'Seek knowledge from the cradle to the grave.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'child reading book', ageGroup: '4-8', content: [{type: 'paragraph', text: 'The first revelation to Prophet Muhammad (PBUH) was "Iqra" (Read!). Islam places great emphasis on learning.'}]},
  { id: 'story-21', title: 'The Story of Habil and Qabil', description: 'The first murder in human history.', moral: 'Jealousy and anger can lead to terrible sins.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'two brothers conflict', ageGroup: '9-16', content: [{type: 'paragraph', text: 'The story of Adam\'s (AS) sons, Habil (Abel) and Qabil (Cain), and how jealousy led to murder.'}]},
  { id: 'story-22', title: 'Prophet Shu\'ayb (AS) and Fair Dealing', description: 'Prophet Shu\'ayb (AS) called his people to honesty in trade.', moral: 'Be honest and just in all your dealings and transactions.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'market scales justice', ageGroup: '9-16', content: [{type: 'paragraph', text: 'Prophet Shu\'ayb (AS) warned the people of Madyan against cheating in weights and measures.'}]},
  { id: 'story-23', title: 'The Parable of Two Gardens', description: 'A Quranic parable about gratitude and arrogance.', moral: 'Be grateful for Allah\'s blessings and avoid arrogance.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'two gardens lush barren', ageGroup: '9-16', content: [{type: 'paragraph', text: 'The Quran tells a story of a man proud of his two lush gardens, who forgot to thank Allah and lost them.'}]},
  { id: 'story-24', title: 'Keeping Promises', description: 'The importance of fulfilling promises in Islam.', moral: 'A believer is true to their word and fulfills their commitments.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'hands shaking agreement', ageGroup: '4-8', content: [{type: 'paragraph', text: 'Islam teaches that fulfilling promises is a sign of faith.'}]},
  { id: 'story-25', title: 'The Woman Who Gave Water to a Dog', description: 'An act of kindness that led to forgiveness.', moral: 'Small acts of kindness to any creature can have great rewards.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'woman dog water', ageGroup: '4-8', content: [{type: 'paragraph', text: 'A sinful woman was forgiven by Allah because she quenched the thirst of a dog.'}]},
  { id: 'story-26', title: 'Controlling Anger', description: 'The strength of one who controls their anger.', moral: 'The strong person is not the one who wrestles, but the one who controls themselves when angry.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'person calming down', ageGroup: '9-16', content: [{type: 'paragraph', text: 'Prophet Muhammad (PBUH) taught that true strength lies in controlling one\'s anger.'}]},
  { id: 'story-27', title: 'The Prophet\'s Love for Children', description: 'Examples of Prophet Muhammad\'s (PBUH) kindness to children.', moral: 'Treat children with love, mercy, and playfulness.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'man children playing', ageGroup: '4-8', content: [{type: 'paragraph', text: 'The Prophet (PBUH) was exceptionally kind and affectionate towards children.'}]},
  { id: 'story-28', title: 'The Importance of Salah (Prayer)', description: 'Why prayer is a pillar of Islam.', moral: 'Salah is our direct connection with Allah and a key to success.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'person praying rug', ageGroup: '4-8', content: [{type: 'paragraph', text: 'Salah (prayer) is the second pillar of Islam and a vital part of a Muslim\'s life.'}]},
  { id: 'story-29', title: 'The Story of Dhul-Qarnayn', description: 'A righteous ruler mentioned in the Quran.', moral: 'Use power and resources justly and for the good of people.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'king building wall', ageGroup: '9-16', content: [{type: 'paragraph', text: 'Dhul-Qarnayn traveled the world and built a barrier to protect people from Yajuj and Majuj (Gog and Magog).'}]},
  { id: 'story-30', title: 'The Value of a Date (Charity)', description: 'Even small acts of charity are valuable.', moral: 'Give charity, even if it is as small as half a date.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'hand giving date', ageGroup: '4-8', content: [{type: 'paragraph', text: 'Prophet Muhammad (PBUH) emphasized giving charity, even if with a small amount.'}]},
  { id: 'story-31', title: 'Good Manners with Neighbors', description: 'How Islam teaches us to treat our neighbors.', moral: 'Be kind and considerate towards your neighbors.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'neighbors talking friendly', ageGroup: '4-8', content: [{type: 'paragraph', text: 'Islam places great importance on treating neighbors well, regardless of their faith.'}]},
  { id: 'story-32', title: 'The Prohibition of Backbiting (Gheebah)', description: 'Why backbiting is a major sin.', moral: 'Avoid speaking ill of others in their absence.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'people whispering secret', ageGroup: '9-16', content: [{type: 'paragraph', text: 'The Quran likens backbiting to eating the flesh of one\'s dead brother.'}]},
  { id: 'story-33', title: 'The Story of the Prophet\'s Shield', description: 'An example of Prophet Muhammad\'s (PBUH) justice with a non-Muslim.', moral: 'Uphold justice for all, irrespective of faith or background.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'shield justice court', ageGroup: '9-16', content: [{type: 'paragraph', text: 'A story where the Prophet (PBUH) judged fairly in a dispute involving a Muslim and a Jew over a shield.'}]},
  { id: 'story-34', title: 'The Importance of Intention (Niyyah)', description: 'Actions are judged by intentions.', moral: 'Ensure your intentions are sincere and for the sake of Allah.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'heart light sincere', ageGroup: '9-16', content: [{type: 'paragraph', text: 'A famous Hadith states that actions are but by intentions, and every man shall have but that which he intended.'}]},
  { id: 'story-35', title: 'Tale of Two Brothers and a Shared Inheritance', description: 'A lesson in fairness and brotherhood.', moral: 'Be fair and loving with your siblings.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'brothers sharing happy', ageGroup: '4-8', content: [{type: 'paragraph', text: 'Two brothers who inherited land decided to share their harvest in a special, selfless way, earning Allah\'s pleasure.'}]},
  { id: 'story-36', title: 'The Man Who Planted a Tree', description: 'The reward of planting for others to benefit.', moral: 'Good deeds that benefit others continue to earn rewards even after death.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'man planting tree', ageGroup: '4-8', content: [{type: 'paragraph', text: 'A man planted a tree from which humans and animals would eat, earning him continuous reward.'}]},
  { id: 'story-37', title: 'The King Who Learned Humility', description: 'An arrogant king learns a lesson in humility.', moral: 'Pride leads to downfall; humility is a virtue.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'king humble servant', ageGroup: '9-16', content: [{type: 'paragraph', text: 'A proud king was humbled by a simple, wise dervish, teaching him the true meaning of power.'}]},
  { id: 'story-38', title: 'The Weaver and His Trust in Allah', description: 'A story about Tawakkul (trust in Allah).', moral: 'Do your best and then trust Allah for the outcome.', thumbnailUrl: 'https://placehold.co/300x200.png', imageAiHint: 'weaver loom trust', ageGroup: '4-8', content: [{type: 'paragraph', text: 'A weaver always said "Alhamdulillah" for whatever happened, showing deep trust in Allah\'s plan.'}]}
];
