
import type { ColoringPage } from '@/lib/types';

export const coloringPagesData: ColoringPage[] = [
  // Mosques & Architecture (5)
  {
    id: 'coloring-mosque-1',
    title: 'Grand Blue Mosque',
    description: 'A grand mosque with a large central dome and two minarets.',
    imageUrl: '/assets/images/coloring/outlines/outline-mosque-1.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-mosque-1.png',
    imageAiHint: 'grand mosque line art',
    coloredImageAiHint: 'grand mosque blue sky',
    tags: ['Architecture', 'Mosque'],
  },
  {
    id: 'coloring-mosque-2',
    title: 'Desert Oasis Mosque',
    description: 'A simple, beautiful mosque nestled among palm trees.',
    imageUrl: '/assets/images/coloring/outlines/outline-mosque-2.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-mosque-2.png',
    imageAiHint: 'desert mosque line art',
    coloredImageAiHint: 'desert mosque palm trees',
    tags: ['Architecture', 'Mosque'],
  },
  {
    id: 'coloring-kaaba',
    title: 'The Holy Kaaba',
    description: 'A simple outline of the Holy Kaaba in Makkah.',
    imageUrl: '/assets/images/coloring/outlines/outline-kaaba.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-kaaba.png',
    imageAiHint: 'kaaba outline simple',
    coloredImageAiHint: 'kaaba makkah gold',
    tags: ['Hajj', 'Makkah'],
  },
  {
    id: 'coloring-mosque-interior',
    title: 'Ornate Mosque Interior',
    description: 'Color the beautiful arches and windows inside a mosque.',
    imageUrl: '/assets/images/coloring/outlines/outline-mosque-interior.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-mosque-interior.png',
    imageAiHint: 'mosque interior line art',
    coloredImageAiHint: 'mosque interior colorful',
    tags: ['Architecture', 'Pattern'],
  },
  {
    id: 'coloring-minaret',
    title: 'Tall Minaret',
    description: 'A single, tall minaret reaching towards the sky.',
    imageUrl: '/assets/images/coloring/outlines/outline-minaret.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-minaret.png',
    imageAiHint: 'mosque minaret drawing',
    coloredImageAiHint: 'mosque minaret sky',
    tags: ['Architecture', 'Mosque'],
  },
  // Ramadan & Eid (5)
  {
    id: 'coloring-ramadan-lantern',
    title: 'Ramadan Lantern',
    description: 'A festive "Fanoos" lantern to celebrate the spirit of Ramadan.',
    imageUrl: '/assets/images/coloring/outlines/outline-ramadan-lantern.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-ramadan-lantern.png',
    imageAiHint: 'ramadan lantern outline',
    coloredImageAiHint: 'ramadan lantern glowing',
    tags: ['Ramadan', 'Celebration'],
  },
  {
    id: 'coloring-crescent-moon',
    title: 'Crescent Moon & Star',
    description: 'The classic symbol of a crescent moon and a star.',
    imageUrl: '/assets/images/coloring/outlines/outline-crescent-moon.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-crescent-moon.png',
    imageAiHint: 'crescent moon star outline',
    coloredImageAiHint: 'crescent moon star night',
    tags: ['Ramadan', 'Symbol'],
  },
  {
    id: 'coloring-iftar-table',
    title: 'Iftar Feast',
    description: 'A table set with dates, water, and yummy food for Iftar.',
    imageUrl: '/assets/images/coloring/outlines/outline-iftar-table.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-iftar-table.png',
    imageAiHint: 'iftar table line drawing',
    coloredImageAiHint: 'iftar food table',
    tags: ['Ramadan', 'Food'],
  },
  {
    id: 'coloring-eid-gifts',
    title: 'Eid Gifts',
    description: 'A stack of beautifully wrapped gifts for Eid.',
    imageUrl: '/assets/images/coloring/outlines/outline-eid-gifts.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-eid-gifts.png',
    imageAiHint: 'eid gifts drawing',
    coloredImageAiHint: 'eid gifts colorful',
    tags: ['Eid', 'Celebration'],
  },
  {
    id: 'coloring-eid-mubarak',
    title: 'Eid Mubarak Sign',
    description: 'A festive sign that says "Eid Mubarak" with decorations.',
    imageUrl: '/assets/images/coloring/outlines/outline-eid-mubarak.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-eid-mubarak.png',
    imageAiHint: 'eid mubarak text drawing',
    coloredImageAiHint: 'eid mubarak sign festive',
    tags: ['Eid', 'Celebration'],
  },
  // Calligraphy & Patterns (5)
  {
    id: 'coloring-calligraphy-allah',
    title: 'Allah Calligraphy',
    description: 'Elegant Arabic calligraphy of the name "Allah".',
    imageUrl: '/assets/images/coloring/outlines/outline-calligraphy-allah.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-calligraphy-allah.png',
    imageAiHint: 'arabic calligraphy allah outline',
    coloredImageAiHint: 'arabic calligraphy allah gold',
    tags: ['Calligraphy', 'Islamic Art'],
  },
  {
    id: 'coloring-calligraphy-muhammad',
    title: 'Muhammad (PBUH) Calligraphy',
    description: 'Beautiful Arabic calligraphy of the name "Muhammad".',
    imageUrl: '/assets/images/coloring/outlines/outline-calligraphy-muhammad.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-calligraphy-muhammad.png',
    imageAiHint: 'arabic calligraphy muhammad outline',
    coloredImageAiHint: 'arabic calligraphy muhammad green',
    tags: ['Calligraphy', 'Islamic Art'],
  },
  {
    id: 'coloring-bismillah-calligraphy',
    title: 'Bismillah Calligraphy',
    description: 'The phrase "Bismillah" in stunning calligraphy.',
    imageUrl: '/assets/images/coloring/outlines/outline-bismillah-calligraphy.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-bismillah-calligraphy.png',
    imageAiHint: 'bismillah calligraphy line art',
    coloredImageAiHint: 'bismillah calligraphy ornate',
    tags: ['Calligraphy', 'Islamic Art'],
  },
  {
    id: 'coloring-geometric-pattern-1',
    title: 'Islamic Star Pattern',
    description: 'An intricate star-shaped geometric pattern to color.',
    imageUrl: '/assets/images/coloring/outlines/outline-geometric-pattern-1.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-geometric-pattern-1.png',
    imageAiHint: 'islamic geometric pattern outline',
    coloredImageAiHint: 'islamic geometric pattern blue',
    tags: ['Pattern', 'Islamic Art'],
  },
  {
    id: 'coloring-geometric-pattern-2',
    title: 'Woven Squares Pattern',
    description: 'A repeating pattern of woven squares and shapes.',
    imageUrl: '/assets/images/coloring/outlines/outline-geometric-pattern-2.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-geometric-pattern-2.png',
    imageAiHint: 'islamic pattern outline simple',
    coloredImageAiHint: 'islamic pattern colorful',
    tags: ['Pattern', 'Islamic Art'],
  },
  // People & Manners (5)
  {
    id: 'coloring-kids-sharing',
    title: 'Children Sharing',
    description: 'A heartwarming scene of two children sharing dates.',
    imageUrl: '/assets/images/coloring/outlines/outline-kids-sharing.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-kids-sharing.png',
    imageAiHint: 'kids sharing food outline',
    coloredImageAiHint: 'children sharing food',
    tags: ['Manners', 'Friendship'],
  },
  {
    id: 'coloring-child-praying',
    title: 'Child Praying',
    description: 'A child making Dua (supplication) with raised hands.',
    imageUrl: '/assets/images/coloring/outlines/outline-child-praying.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-child-praying.png',
    imageAiHint: 'child praying line art',
    coloredImageAiHint: 'child praying peacefully',
    tags: ['Prayer', 'Manners'],
  },
  {
    id: 'coloring-giving-charity',
    title: 'Giving Charity',
    description: 'A child placing a coin in a charity box.',
    imageUrl: '/assets/images/coloring/outlines/outline-giving-charity.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-giving-charity.png',
    imageAiHint: 'child charity box outline',
    coloredImageAiHint: 'child giving charity',
    tags: ['Charity', 'Manners'],
  },
  {
    id: 'coloring-helping-elderly',
    title: 'Helping an Elder',
    description: 'A child helping an elderly person walk.',
    imageUrl: '/assets/images/coloring/outlines/outline-helping-elderly.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-helping-elderly.png',
    imageAiHint: 'child helping elderly drawing',
    coloredImageAiHint: 'child helping grandparent',
    tags: ['Respect', 'Manners'],
  },
  {
    id: 'coloring-reading-quran',
    title: 'Reading Quran',
    description: 'Two children sitting together and reading the Quran.',
    imageUrl: '/assets/images/coloring/outlines/outline-reading-quran.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-reading-quran.png',
    imageAiHint: 'kids reading quran outline',
    coloredImageAiHint: 'children reading quran',
    tags: ['Quran', 'Learning'],
  },
  // Objects & Items (5)
  {
    id: 'coloring-prayer-mat',
    title: 'Ornate Prayer Mat',
    description: 'A prayer mat with intricate patterns waiting for your colors.',
    imageUrl: '/assets/images/coloring/outlines/outline-prayer-mat.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-prayer-mat.png',
    imageAiHint: 'prayer rug outline patterns',
    coloredImageAiHint: 'prayer rug colorful',
    tags: ['Prayer', 'Islamic Art'],
  },
  {
    id: 'coloring-tasbih',
    title: 'Prayer Beads (Tasbih)',
    description: 'A string of prayer beads to color.',
    imageUrl: '/assets/images/coloring/outlines/outline-tasbih.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-tasbih.png',
    imageAiHint: 'tasbih beads outline',
    coloredImageAiHint: 'tasbih beads colorful',
    tags: ['Prayer', 'Items'],
  },
  {
    id: 'coloring-quran-stand',
    title: 'Quran on a Stand',
    description: 'An open Quran resting on a wooden stand.',
    imageUrl: '/assets/images/coloring/outlines/outline-quran-stand.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-quran-stand.png',
    imageAiHint: 'quran stand line art',
    coloredImageAiHint: 'quran on stand wood',
    tags: ['Quran', 'Items'],
  },
  {
    id: 'coloring-kufi-cap',
    title: 'Prayer Cap (Kufi)',
    description: 'A traditional prayer cap with simple patterns.',
    imageUrl: '/assets/images/coloring/outlines/outline-kufi-cap.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-kufi-cap.png',
    imageAiHint: 'kufi cap outline',
    coloredImageAiHint: 'prayer cap white embroidered',
    tags: ['Prayer', 'Items'],
  },
  {
    id: 'coloring-oud-perfume',
    title: 'Oud Perfume Bottle',
    description: 'An ornate bottle of traditional Oud perfume.',
    imageUrl: '/assets/images/coloring/outlines/outline-oud-perfume.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-oud-perfume.png',
    imageAiHint: 'perfume bottle ornate drawing',
    coloredImageAiHint: 'oud perfume bottle decorative',
    tags: ['Culture', 'Items'],
  },
  // Nature & Animals (5)
  {
    id: 'coloring-camel-desert',
    title: 'Camel in the Desert',
    description: 'A majestic camel walking in the desert with pyramids in the back.',
    imageUrl: '/assets/images/coloring/outlines/outline-camel-desert.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-camel-desert.png',
    imageAiHint: 'camel desert line art',
    coloredImageAiHint: 'camel desert sunset',
    tags: ['Animals', 'Nature'],
  },
  {
    id: 'coloring-pomegranate',
    title: 'Pomegranate Fruit',
    description: 'A juicy pomegranate, a fruit mentioned in the Quran.',
    imageUrl: '/assets/images/coloring/outlines/outline-pomegranate.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-pomegranate.png',
    imageAiHint: 'pomegranate fruit outline',
    coloredImageAiHint: 'pomegranate fruit red',
    tags: ['Nature', 'Food'],
  },
  {
    id: 'coloring-olive-branch',
    title: 'Olive Branch',
    description: 'A branch with olives, a symbol of peace and blessings.',
    imageUrl: '/assets/images/coloring/outlines/outline-olive-branch.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-olive-branch.png',
    imageAiHint: 'olive branch line drawing',
    coloredImageAiHint: 'olive branch green',
    tags: ['Nature', 'Symbol'],
  },
  {
    id: 'coloring-hoopoe-bird',
    title: 'The Hoopoe Bird',
    description: 'The intelligent Hoopoe bird from the story of Prophet Sulaiman (AS).',
    imageUrl: '/assets/images/coloring/outlines/outline-hoopoe-bird.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-hoopoe-bird.png',
    imageAiHint: 'hoopoe bird line art',
    coloredImageAiHint: 'hoopoe bird colorful',
    tags: ['Animals', 'Prophets'],
  },
  {
    id: 'coloring-beehive',
    title: 'Busy Bees',
    description: 'Bees making honey, a creature mentioned for its wonders in the Quran.',
    imageUrl: '/assets/images/coloring/outlines/outline-beehive.png',
    coloredImageUrl: '/assets/images/coloring/colored/colored-beehive.png',
    imageAiHint: 'beehive honey drawing',
    coloredImageAiHint: 'beehive busy bees',
    tags: ['Animals', 'Nature'],
  },
];
