
import type { Game } from '@/lib/types';

export const gameTypes: Game[] = [
  {
    id: 'islamic-quiz',
    title: 'Islamic Quiz Challenge',
    description: 'Test your knowledge about Islamic principles, history, and prophets.',
    type: 'quiz',
    href: '/games/quiz/general-knowledge-1',
    icon: 'HelpCircle',
    ageGroup: '9-16',
    imageAiHint: 'quiz question mark',
    imagePath: '/assets/images/games/cards/game-islamic-quiz-card.png',
  },
  {
    id: 'prophets-puzzle',
    title: 'Prophets Jigsaw Puzzle',
    description: 'Piece together beautiful images related to stories of the Prophets.',
    type: 'puzzle',
    href: '/games/puzzle/prophet-noah-ark',
    icon: 'Puzzle',
    ageGroup: '4-8',
    imageAiHint: 'jigsaw puzzle kids',
    imagePath: '/assets/images/games/cards/game-prophets-puzzle-card.png',
  },
  {
    id: 'ethics-memory-match',
    title: 'Islamic Ethics Memory Match',
    description: 'Match pairs of cards related to good manners and Islamic ethics.',
    type: 'memory-match',
    href: '/games/memory-match/good-deeds-1',
    icon: 'Brain',
    ageGroup: '4-8',
    imageAiHint: 'memory game cards',
    imagePath: '/assets/images/games/cards/game-ethics-memory-match-card.png',
  },
  {
    id: 'coloring-fun',
    title: 'Digital Coloring',
    description: 'Unleash your creativity and get your artwork scored by an AI teacher.',
    type: 'coloring',
    href: '/coloring',
    icon: 'Palette',
    ageGroup: '4-8',
    imageAiHint: 'kids coloring islamic art',
    imagePath: '/assets/images/features/home-feature-coloring-fun.png',
  },
   {
    id: 'advanced-fiqh-quiz',
    title: 'Advanced Fiqh Quiz',
    description: 'A more challenging quiz on Islamic jurisprudence for older youngsters.',
    type: 'quiz',
    href: '/games/quiz/fiqh-basics-1',
    icon: 'HelpCircle',
    ageGroup: '9-16',
    imageAiHint: 'islamic law book',
    imagePath: '/assets/images/games/cards/game-advanced-fiqh-quiz-card.png',
  },
  {
    id: 'arabic-alphabet-match',
    title: 'Arabic Alphabet Fun',
    description: 'Match Arabic letters! A fun way to start learning the alphabet.',
    type: 'memory-match',
    href: '/games/memory-match/arabic-letters-1',
    icon: 'SpellCheck',
    ageGroup: '4-8',
    imageAiHint: 'arabic letters colorful',
    imagePath: '/assets/images/games/cards/game-arabic-alphabet-match-card.png',
  },
  {
    id: 'mosque-builder-puzzle',
    title: 'Mosque Builder Puzzle',
    description: 'Build famous mosques from around the world with these jigsaw puzzles.',
    type: 'puzzle',
    href: '/games/puzzle/famous-mosque-1',
    icon: 'Puzzle',
    ageGroup: '9-16',
    imageAiHint: 'mosque building blocks',
    imagePath: '/assets/images/games/cards/game-mosque-builder-puzzle-card.png',
  },
  {
    id: 'halal-haram-sort',
    title: 'Halal & Haram Sort',
    description: 'Learn about Halal and Haram concepts by sorting items. (Conceptual)',
    type: 'quiz', 
    href: '/games/quiz/halal-haram-1', 
    icon: 'HelpCircle',
    ageGroup: '9-16',
    imageAiHint: 'food choices ethics',
    imagePath: '/assets/images/games/cards/game-halal-haram-sort-card.png',
  },
  {
    id: 'good-deeds-adventure',
    title: 'Good Deeds Adventure',
    description: 'Embark on an adventure where you make choices based on Islamic ethics. (Conceptual)',
    type: 'adventure', 
    href: '/games/adventure/kindness-journey-1', 
    icon: 'Sparkles',
    ageGroup: '4-8',
    imageAiHint: 'path choices kids',
    imagePath: '/assets/images/games/cards/game-good-deeds-adventure-card.png',
  },
  {
    id: 'ramadan-facts-quiz',
    title: 'Ramadan Facts Quiz',
    description: 'Learn interesting facts about the blessed month of Ramadan.',
    type: 'quiz',
    href: '/games/quiz/ramadan-facts-1',
    icon: 'HelpCircle',
    ageGroup: '4-8',
    imageAiHint: 'ramadan moon lantern',
    imagePath: '/assets/images/games/cards/game-ramadan-facts-quiz-card.png',
  },
  {
    id: 'prayer-times-puzzle',
    title: 'Prayer Times Puzzle',
    description: 'Match prayer names with their times or symbols.',
    type: 'puzzle',
    href: '/games/puzzle/prayer-times-symbols',
    icon: 'Puzzle',
    ageGroup: '4-8',
    imageAiHint: 'prayer times clock',
    imagePath: '/assets/images/games/cards/game-prayer-times-puzzle-card.png',
  },
  {
    id: 'wudu-steps-match',
    title: 'Wudu Steps Match-Up',
    description: 'Learn the steps of Wudu (ablution) by matching images or descriptions.',
    type: 'memory-match',
    href: '/games/memory-match/wudu-steps',
    icon: 'Brain',
    ageGroup: '4-8',
    imageAiHint: 'water hands cleaning',
    imagePath: '/assets/images/games/cards/game-wudu-steps-match-card.png',
  },
  {
    id: 'pillars-of-islam-quiz',
    title: 'Pillars of Islam Quiz',
    description: 'Test your knowledge on the five pillars of Islam.',
    type: 'quiz',
    href: '/games/quiz/pillars-islam-1',
    icon: 'HelpCircle',
    ageGroup: '9-16',
    imageAiHint: 'five pillars symbols',
    imagePath: '/assets/images/games/cards/game-pillars-of-islam-quiz-card.png',
  },
];
