
import type { Game } from '@/lib/types';

export const gameTypes: Game[] = [
  {
    id: 'islamic-quiz',
    title: 'Islamic Quiz Challenge',
    description: 'Test your knowledge about Islamic principles, history, and prophets.',
    type: 'quiz',
    href: '/games/quiz/general-knowledge-1',
    icon: 'HelpCircle',
    ageGroup: '9-16',
    imageAiHint: 'quiz question mark',
  },
  {
    id: 'prophets-puzzle',
    title: 'Prophets Jigsaw Puzzle',
    description: 'Piece together beautiful images related to stories of the Prophets.',
    type: 'puzzle',
    href: '/games/puzzle/prophet-noah-ark',
    icon: 'Puzzle',
    ageGroup: '4-8',
    imageAiHint: 'jigsaw puzzle kids',
  },
  {
    id: 'ethics-memory-match',
    title: 'Islamic Ethics Memory Match',
    description: 'Match pairs of cards related to good manners and Islamic ethics.',
    type: 'memory-match',
    href: '/games/memory-match/good-deeds-1',
    icon: 'Brain',
    ageGroup: '4-8',
    imageAiHint: 'memory game cards',
  },
   {
    id: 'advanced-fiqh-quiz',
    title: 'Advanced Fiqh Quiz',
    description: 'A more challenging quiz on Islamic jurisprudence for older youngsters.',
    type: 'quiz',
    href: '/games/quiz/fiqh-basics-1',
    icon: 'HelpCircle',
    ageGroup: '9-16',
    imageAiHint: 'islamic law book',
  },
  {
    id: 'arabic-alphabet-match',
    title: 'Arabic Alphabet Fun',
    description: 'Match Arabic letters! A fun way to start learning the alphabet.',
    type: 'memory-match',
    href: '/games/memory-match/arabic-letters-1',
    icon: 'SpellCheck', // We'll need to add SpellCheck or use an existing one like 'BookOpen'
    ageGroup: '4-8',
    imageAiHint: 'arabic letters colorful',
  },
  {
    id: 'mosque-builder-puzzle',
    title: 'Mosque Builder Puzzle',
    description: 'Build famous mosques from around the world with these jigsaw puzzles.',
    type: 'puzzle',
    href: '/games/puzzle/famous-mosque-1',
    icon: 'Puzzle',
    ageGroup: '9-16',
    imageAiHint: 'mosque building blocks',
  },
  {
    id: 'halal-haram-sort',
    title: 'Halal & Haram Sort',
    description: 'Learn about Halal and Haram concepts by sorting items. (Conceptual)',
    type: 'quiz', // Could be a custom game type later
    href: '/games/quiz/halal-haram-1', // Placeholder href
    icon: 'HelpCircle',
    ageGroup: '9-16',
    imageAiHint: 'food choices ethics',
  },
  {
    id: 'good-deeds-adventure',
    title: 'Good Deeds Adventure',
    description: 'Embark on an adventure where you make choices based on Islamic ethics. (Conceptual)',
    type: 'adventure', // New conceptual type
    href: '/games/adventure/kindness-journey-1', // Placeholder href
    icon: 'Sparkles',
    ageGroup: '4-8',
    imageAiHint: 'path choices kids',
  },
  {
    id: 'ramadan-facts-quiz',
    title: 'Ramadan Facts Quiz',
    description: 'Learn interesting facts about the blessed month of Ramadan.',
    type: 'quiz',
    href: '/games/quiz/ramadan-facts-1',
    icon: 'HelpCircle',
    ageGroup: '4-8',
    imageAiHint: 'ramadan moon lantern',
  },
  {
    id: 'prayer-times-puzzle',
    title: 'Prayer Times Puzzle',
    description: 'Match prayer names with their times or symbols.',
    type: 'puzzle',
    href: '/games/puzzle/prayer-times-symbols',
    icon: 'Puzzle',
    ageGroup: '4-8',
    imageAiHint: 'prayer times clock',
  },
  {
    id: 'wudu-steps-match',
    title: 'Wudu Steps Match-Up',
    description: 'Learn the steps of Wudu (ablution) by matching images or descriptions.',
    type: 'memory-match',
    href: '/games/memory-match/wudu-steps',
    icon: 'Brain',
    ageGroup: '4-8',
    imageAiHint: 'water hands cleaning',
  },
  {
    id: 'pillars-of-islam-quiz',
    title: 'Pillars of Islam Quiz',
    description: 'Test your knowledge on the five pillars of Islam.',
    type: 'quiz',
    href: '/games/quiz/pillars-islam-1',
    icon: 'HelpCircle',
    ageGroup: '9-16',
    imageAiHint: 'five pillars symbols',
  },
];
