
import type { Dua } from '@/lib/types';

export const dummyDuas: Dua[] = [
  {
    id: 'dua-before-eating',
    title: 'Dua Before Eating',
    arabic: 'بِسْمِ اللهِ',
    translation: 'In the name of Allah.',
    transliteration: 'Bismillah.',
    audioUrl: '/audio/bismillah.mp3',
    explanation: 'Recite this dua before starting your meal to seek blessings from Allah.',
    ageGroup: '4-8',
    imageAiHint: 'food plate kids',
    imagePath: 'https://images.unsplash.com/photo-1576867757603-05b134ebc379?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxsdW5jaHxlbnwwfHx8fDE3NTA2NzY4NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    mainImagePath: '/assets/images/duas/dua-before-eating-main.png',
  },
  {
    id: 'dua-after-eating',
    title: 'Dua After Eating',
    arabic: 'الْحَمْدُ للهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    translation: 'All praise is for Allah who fed us and gave us drink, and made us Muslims.',
    transliteration: 'Alhamdu lillahil-ladhi at\'amana wasaqana waja\'alana Muslimin.',
    audioUrl: '/audio/alhamdulillah_eating.mp3',
    explanation: 'Thank Allah for the food and drink He has provided after finishing your meal.',
    ageGroup: '4-8',
    imageAiHint: 'empty plate thankful',
    imagePath: '/assets/images/duas/dua-after-eating-card.png',
    mainImagePath: '/assets/images/duas/dua-after-eating-main.png',
  },
  {
    id: 'dua-before-sleeping',
    title: 'Dua Before Sleeping',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    translation: 'In Your name O Allah, I live and die.',
    transliteration: 'Bismika Allahumma amutu wa ahya.',
    audioUrl: '/audio/bismika_allahumma.mp3',
    explanation: 'Recite this dua before going to sleep, entrusting yourself to Allah.',
    ageGroup: '9-16',
    imageAiHint: 'moon stars child',
    imagePath: '/assets/images/duas/dua-before-sleeping-card.png',
    mainImagePath: '/assets/images/duas/dua-before-sleeping-main.png',
  },
  {
    id: 'dua-waking-up',
    title: 'Dua After Waking Up',
    arabic: 'الْحَمْدُ للهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    translation: 'All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.',
    transliteration: 'Alhamdu lillahil-ladhi ahyana ba\'da ma amatana wa ilaihin-nushur.',
    audioUrl: '/audio/alhamdulillah_waking.mp3',
    explanation: 'Thank Allah for giving you another day when you wake up.',
    ageGroup: '9-16',
    imageAiHint: 'sunshine window child',
    imagePath: '/assets/images/duas/dua-waking-up-card.png',
    mainImagePath: '/assets/images/duas/dua-waking-up-main.png',
  },
  {
    id: 'dua-entering-home',
    title: 'Dua When Entering Home',
    arabic: 'بِسْـمِ اللهِ وَلَجْنـا، وَبِسْـمِ اللهِ خَـرَجْنـا، وَعَلـى رَبِّنـا تَوَكّلْـنا',
    translation: 'In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we depend.',
    transliteration: 'Bismillahi walajna, wabismillahi kharajna, wa \'ala rabbina tawakkalna.',
    audioUrl: '/audio/entering_home.mp3',
    explanation: 'Recite this dua when entering your home to invite blessings and protection.',
    ageGroup: '4-8',
    imageAiHint: 'door open welcome',
    imagePath: '/assets/images/duas/dua-entering-home-card.png',
    mainImagePath: '/assets/images/duas/dua-entering-home-main.png',
  },
  {
    id: 'dua-leaving-home',
    title: 'Dua When Leaving Home',
    arabic: 'بِسْمِ اللهِ، تَوَكَّلْتُ عَلَى اللهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ',
    translation: 'In the name of Allah, I have placed my trust in Allah, there is no might and no power except by Allah.',
    transliteration: 'Bismillahi, tawakkaltu \'alallah, wa la hawla wa la quwwata illa billah.',
    audioUrl: '/audio/leaving_home.mp3',
    explanation: 'Recite this dua when leaving your home for Allah\'s protection and guidance.',
    ageGroup: '4-8',
    imageAiHint: 'child waving goodbye',
    imagePath: '/assets/images/duas/dua-leaving-home-card.png',
    mainImagePath: '/assets/images/duas/dua-leaving-home-main.png',
  },
  {
    id: 'dua-entering-toilet',
    title: 'Dua Before Entering Toilet',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    translation: 'O Allah, I seek protection in You from the male and female evil spirits.',
    transliteration: 'Allahumma inni a\'udhu bika minal-khubuthi wal-khabaith.',
    audioUrl: '/audio/entering_toilet.mp3',
    explanation: 'Seek Allah\'s protection from evil before entering the toilet.',
    ageGroup: '4-8',
    imageAiHint: 'closed door bathroom',
    imagePath: '/assets/images/duas/dua-entering-toilet-card.png',
    mainImagePath: '/assets/images/duas/dua-entering-toilet-main.png',
  },
  {
    id: 'dua-leaving-toilet',
    title: 'Dua After Leaving Toilet',
    arabic: 'غُفْرَانَكَ',
    translation: 'I seek Your forgiveness.',
    transliteration: 'Ghufranak.',
    audioUrl: '/audio/leaving_toilet.mp3',
    explanation: 'Ask for Allah\'s forgiveness after leaving the toilet.',
    ageGroup: '4-8',
    imageAiHint: 'washing hands clean',
    imagePath: '/assets/images/duas/dua-leaving-toilet-card.png',
    mainImagePath: '/assets/images/duas/dua-leaving-toilet-main.png',
  },
  {
    id: 'dua-wearing-clothes',
    title: 'Dua When Wearing Clothes',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا (الثَّوْبَ) وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    translation: 'All Praise is for Allah who has clothed me with this (garment) and provided it for me without any strength or power on my part.',
    transliteration: 'Alhamdu lillahil-ladhi kasani hadha (ath-thawb) warazaqaneehi min ghayri hawlin minni wala quwwah.',
    audioUrl: '/audio/wearing_clothes.mp3',
    explanation: 'Thank Allah for the clothes He has provided.',
    ageGroup: '4-8',
    imageAiHint: 'child dressing smiling',
    imagePath: '/assets/images/duas/dua-wearing-clothes-card.png',
    mainImagePath: '/assets/images/duas/dua-wearing-clothes-main.png',
  },
  {
    id: 'dua-for-parents',
    title: 'Dua For Parents',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    translation: 'My Lord, have mercy upon them as they brought me up [when I was] small.',
    transliteration: 'Rabbir hamhuma kama rabbayani sagheera.',
    audioUrl: '/audio/for_parents.mp3',
    explanation: 'A beautiful Quranic dua to pray for mercy for your parents.',
    ageGroup: '4-8',
    imageAiHint: 'family hug parents',
    imagePath: '/assets/images/duas/dua-for-parents-card.png',
    mainImagePath: '/assets/images/duas/dua-for-parents-main.png',
  },
  {
    id: 'dua-seeking-knowledge',
    title: 'Dua For Seeking Knowledge',
    arabic: 'رَّبِّ زِدْنِي عِلْمًا',
    translation: 'My Lord, increase me in knowledge.',
    transliteration: 'Rabbi zidni \'ilma.',
    audioUrl: '/audio/seeking_knowledge.mp3',
    explanation: 'Ask Allah to increase your knowledge and understanding.',
    ageGroup: '9-16',
    imageAiHint: 'child reading book',
    imagePath: '/assets/images/duas/dua-seeking-knowledge-card.png',
    mainImagePath: '/assets/images/duas/dua-seeking-knowledge-main.png',
  },
  {
    id: 'dua-before-studying',
    title: 'Dua Before Studying',
    arabic: 'اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي، وَعَلِّمْنِي مَا يَنْفَعُنِي، وَزِدْنِي عِلْمًا',
    translation: 'O Allah! Make beneficial for me what You have taught me, and teach me what will benefit me, and increase me in knowledge.',
    transliteration: 'Allahumma-infa\'ni bima \'allamtani, wa \'allimni ma yanfa\'uni, wa zidni \'ilma.',
    audioUrl: '/audio/before_studying.mp3',
    explanation: 'Recite this dua before starting your studies for focus and benefit.',
    ageGroup: '9-16',
    imageAiHint: 'student desk books',
    imagePath: '/assets/images/duas/dua-before-studying-card.png',
    mainImagePath: '/assets/images/duas/dua-before-studying-main.png',
  },
  {
    id: 'dua-sneezing',
    title: 'Dua When You Sneeze',
    arabic: 'الْحَمْدُ لِلَّهِ',
    translation: 'All praise is for Allah.',
    transliteration: 'Alhamdulillah.',
    audioUrl: '/audio/sneezing.mp3',
    explanation: 'Say this when you sneeze. If someone else says it, reply with "YarhamukAllah" (May Allah have mercy on you).',
    ageGroup: '4-8',
    imageAiHint: 'child sneezing tissue',
    imagePath: '/assets/images/duas/dua-sneezing-card.png',
    mainImagePath: '/assets/images/duas/dua-sneezing-main.png',
  },
  {
    id: 'dua-visiting-sick',
    title: 'Dua When Visiting The Sick',
    arabic: 'لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ',
    translation: 'Do not worry, it will be a purification (for sins), if Allah wills.',
    transliteration: 'La ba\'sa tahurun inshaAllah.',
    audioUrl: '/audio/visiting_sick.mp3',
    explanation: 'Console and pray for a sick person with this dua.',
    ageGroup: '9-16',
    imageAiHint: 'child visiting friend',
    imagePath: '/assets/images/duas/dua-visiting-sick-card.png',
    mainImagePath: '/assets/images/duas/dua-visiting-sick-main.png',
  },
];
