
import type { QuranVerse } from '@/lib/types';

export const dummyQuranVerses: QuranVerse[] = [
  {
    id: 'ayatul-kursi',
    surahName: 'Al-Baqarah',
    verseNumber: '2:255',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    translation: 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.',
    tafsir: 'This verse, known as Ayatul Kursi (The Verse of the Throne), is one of the most powerful verses in the Quran. It describes Allah\'s absolute power, knowledge, and sovereignty over the entire universe. Reciting it provides protection and peace.',
    audioUrl: '/audio/ayatul_kursi.mp3',
    ageGroup: '9-16',
    imageAiHint: 'throne light heaven',
    imagePath: '/assets/images/quran/verse-ayatul-kursi-card.png',
    mainImagePath: '/assets/images/quran/verse-ayatul-kursi-main.png',
  },
  {
    id: 'surah-al-fatihah',
    surahName: 'Al-Fatihah',
    verseNumber: '1:1-7',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ الرَّحْمَٰنِ الرَّحِيمِ مَالِكِ يَوْمِ الدِّينِ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
    translation: 'In the name of Allah, the Entirely Merciful, the Especially Merciful. [All] praise is [due] to Allah, Lord of the worlds - The Entirely Merciful, the Especially Merciful, Sovereign of the Day of Recompense. It is You we worship and You we ask for help. Guide us to the straight path - The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.',
    tafsir: 'Surah Al-Fatihah (The Opening) is the first chapter of the Quran. It is a prayer for guidance, a declaration of Allah\'s lordship and mercy, and a fundamental part of Muslim prayer (Salah).',
    audioUrl: '/audio/al_fatihah.mp3',
    ageGroup: '4-8',
    imageAiHint: 'quran open book',
    imagePath: '/assets/images/quran/verse-surah-al-fatihah-card.png',
    mainImagePath: '/assets/images/quran/verse-surah-al-fatihah-main.png',
  },
  {
    id: 'surah-al-ikhlas',
    surahName: 'Al-Ikhlas',
    verseNumber: '112:1-4',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ اللَّهُ الصَّمَدُ لَمْ يَلِدْ وَلَمْ يُولَدْ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    translation: 'Say, "He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, Nor is there to Him any equivalent."',
    tafsir: 'Surah Al-Ikhlas (The Sincerity) affirms the oneness of Allah (Tawhid). It is a concise and powerful declaration of Allah\'s unique nature, rejecting any form of partnership or resemblance to His creation.',
    audioUrl: '/audio/al_ikhlas.mp3',
    ageGroup: '4-8',
    imageAiHint: 'islamic pattern unity',
    imagePath: '/assets/images/quran/verse-surah-al-ikhlas-card.png',
    mainImagePath: '/assets/images/quran/verse-surah-al-ikhlas-main.png',
  },
  {
    id: 'surah-al-nas',
    surahName: 'An-Nas',
    verseNumber: '114:1-6',
    arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ مَلِكِ النَّاسِ إِلَٰهِ النَّاسِ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ مِنَ الْجِنَّةِ وَالنَّاسِ',
    translation: 'Say, "I seek refuge in the Lord of mankind, The Sovereign of mankind, The God of mankind, From the evil of the retreating whisperer - Who whispers [evil] into the breasts of mankind - From among the jinn and mankind."',
    tafsir: 'Surah An-Nas (Mankind) is a prayer for protection from evil whispers and influences, both from jinn and humans. It emphasizes seeking refuge in Allah, the Lord, King, and God of all people.',
    audioUrl: '/audio/an_nas.mp3',
    ageGroup: '4-8',
    imageAiHint: 'protection shield light',
    imagePath: '/assets/images/quran/verse-surah-al-nas-card.png',
    mainImagePath: '/assets/images/quran/verse-surah-al-nas-main.png',
  },
  {
    id: 'surah-al-falaq',
    surahName: 'Al-Falaq',
    verseNumber: '113:1-5',
    arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ مِنْ شَرِّ مَا خَلَقَ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    translation: 'Say, "I seek refuge in the Lord of daybreak, From the evil of that which He created, And from the evil of darkness when it settles, And from the evil of the blowers in knots, And from the evil of an envier when he envies."',
    tafsir: 'Surah Al-Falaq (Daybreak) is a prayer seeking Allah\'s protection from various forms of evil, including the evil of creation, darkness, witchcraft, and envy. It is often recited for safety.',
    audioUrl: '/audio/al_falaq.mp3',
    ageGroup: '4-8',
    imageAiHint: 'daybreak sun rise',
    imagePath: '/assets/images/quran/verse-surah-al-falaq-card.png',
    mainImagePath: '/assets/images/quran/verse-surah-al-falaq-main.png',
  },
  {
    id: 'surah-al-asr',
    surahName: 'Al-Asr',
    verseNumber: '103:1-3',
    arabic: 'وَالْعَصْرِ إِنَّ الْإِنْسَانَ لَفِي خُسْرٍ إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',
    translation: 'By time, indeed, mankind is in loss, Except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience.',
    tafsir: 'Surah Al-Asr (The Declining Day) emphasizes the importance of time, faith, good deeds, and advising one another towards truth and patience as the keys to avoiding loss and achieving success.',
    audioUrl: '/audio/al_asr.mp3',
    ageGroup: '9-16',
    imageAiHint: 'hourglass time path',
    imagePath: '/assets/images/quran/verse-surah-al-asr-card.png',
    mainImagePath: '/assets/images/quran/verse-surah-al-asr-main.png',
  },
  {
    id: 'quran-kindness-parents',
    surahName: 'Al-Isra',
    verseNumber: '17:23',
    arabic: 'وَقَضَىٰ رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا',
    translation: 'And your Lord has decreed that you not worship except Him, and to parents, good treatment.',
    tafsir: 'This verse commands Muslims to worship Allah alone and to treat their parents with utmost kindness and respect. It highlights the high status of parents in Islam.',
    audioUrl: '/audio/kindness_parents.mp3',
    ageGroup: '9-16',
    imageAiHint: 'family loving parents',
    imagePath: '/assets/images/quran/verse-quran-kindness-parents-card.png',
    mainImagePath: '/assets/images/quran/verse-quran-kindness-parents-main.png',
  },
  {
    id: 'quran-speak-good-words',
    surahName: 'Al-Baqarah',
    verseNumber: '2:83',
    arabic: 'وَقُولُوا لِلنَّاسِ حُسْنًا',
    translation: 'And speak to people good [words].',
    tafsir: 'This part of a longer verse emphasizes the importance of speaking kindly and positively to all people. Good speech is a characteristic of a believer.',
    audioUrl: '/audio/good_words.mp3',
    ageGroup: '4-8',
    imageAiHint: 'children talking nicely',
    imagePath: '/assets/images/quran/verse-quran-speak-good-words-card.png',
    mainImagePath: '/assets/images/quran/verse-quran-speak-good-words-main.png',
  },
  {
    id: 'quran-do-not-waste',
    surahName: 'Al-A\'raf',
    verseNumber: '7:31',
    arabic: 'وَكُلُوا وَاشْرَبُوا وَلَا تُسْرِفُوا ۚ إِنَّهُ لَا يُحِبُّ الْمُسْرِفِينَ',
    translation: 'And eat and drink, but be not excessive. Indeed, He likes not those who commit excess.',
    tafsir: 'This verse permits eating and drinking from the good things Allah has provided but warns against extravagance and wastefulness. Moderation is key in Islam.',
    audioUrl: '/audio/do_not_waste.mp3',
    ageGroup: '9-16',
    imageAiHint: 'food balanced meal',
    imagePath: '/assets/images/quran/verse-quran-do-not-waste-card.png',
    mainImagePath: '/assets/images/quran/verse-quran-do-not-waste-main.png',
  },
  {
    id: 'quran-patience-prayer',
    surahName: 'Al-Baqarah',
    verseNumber: '2:153',
    arabic: 'يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
    translation: 'O you who have believed, seek help through patience and prayer. Indeed, Allah is with the patient.',
    tafsir: 'This verse advises believers to seek strength and assistance from Allah through patience and prayer, especially during times of difficulty. It assures that Allah is with those who are patient.',
    audioUrl: '/audio/patience_prayer.mp3',
    ageGroup: '9-16',
    imageAiHint: 'person praying peacefully',
    imagePath: '/assets/images/quran/verse-quran-patience-prayer-card.png',
    mainImagePath: '/assets/images/quran/verse-quran-patience-prayer-main.png',
  },
   {
    id: 'quran-creation-diversity',
    surahName: 'Ar-Rum',
    verseNumber: '30:22',
    arabic: 'وَمِنْ آيَاتِهِ خَلْقُ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافُ أَلْسِنَتِكُمْ وَأَلْوَانِكُمْ ۚ إِنَّ فِي ذَٰلِكَ لَآيَاتٍ لِلْعَالِمِينَ',
    translation: 'And of His signs is the creation of the heavens and the earth and the diversity of your languages and your colors. Indeed, in that are signs for those of knowledge.',
    tafsir: 'This verse highlights the diversity in languages and colors among people as one of Allah\'s magnificent signs, encouraging reflection and appreciation for the variety in His creation.',
    audioUrl: '/audio/creation_diversity.mp3',
    ageGroup: '9-16',
    imageAiHint: 'children diverse world',
    imagePath: '/assets/images/quran/verse-quran-creation-diversity-card.png',
    mainImagePath: '/assets/images/quran/verse-quran-creation-diversity-main.png',
  },
  {
    id: 'quran-forgiveness',
    surahName: 'Az-Zumar',
    verseNumber: '39:53',
    arabic: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ',
    translation: 'Say, "O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful."',
    tafsir: 'A powerful verse of hope, reminding believers that Allah\'s mercy is vast and He forgives all sins for those who sincerely repent. It encourages never to lose hope in His forgiveness.',
    audioUrl: '/audio/forgiveness_allah.mp3',
    ageGroup: '9-16',
    imageAiHint: 'hopeful light sky',
    imagePath: '/assets/images/quran/verse-quran-forgiveness-card.png',
    mainImagePath: '/assets/images/quran/verse-quran-forgiveness-main.png',
  },
];
